@extends('layouts.app')

@section('title', 'Bab Tiga - The Unkindled')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            
            <h2 class="text-center mb-4">Bab Tiga: Abu di Bawah Tulang-Tulang Borreal</h2>
            <hr class="my-4">

            @php
                $naskahLengkap = "Angin berhembus dengan pelan, seperti himne kematian yang dinyanyikan oleh para hantu. Borreal. Kerajaan yang dulunya perak karena kerajaan ini berada di bagian utara dan tertutup oleh salju akan keberadaannya dan pengetahuannya yang membuat kerajaan ini terbilang cukup maju sebelum kehancuran kerajaan ini menghapuskan seluruh peradaban yang ada bahkan sisa-sisa pengetahuannya terkubur di dalam tanah. Dan sekarang, kerajaan itu berubah menjadi monumen batu yang hangus dari sisa kebakaran dan kekacauannya, menara yang dulunya menjulang tinggi itu kini terbelah dan hancur, dan aroma kejayaan yang masih tercium itu di hidung para pengembara yang melewati kerajaan itu hanya bisa mencium aromanya dengan melihat sisa-sisa reruntuhan batu dan jalan yang sudah rusak itu sebagai sejarah yang telah terlupakan.

Sora dan Kaelith berdiri di lengkungan pintu gerbang masuk ke dalam kerajaan itu yang sudah hancur. Prasasti yang terukir di sepanjang rangkanya telah rusak hingga tak bisa dibaca tulisan yang ada pada prasasti itu yang beberapa diantaranya hancur dan yang lainnya terkikis oleh waktu dan darah yang masih membekas di batu-batu prasasti tersebut.

Kaelith menarik jubahnya lebih erat dan mengamati cakrawala, ia berkata pada dirinya sendiri lebih tepatnya setelah melihat kerajaan Borreal itu dengan matanya sendiri. 'Jadi ini kerajaan Borreal. Nafas terakhir dari utara itu yang tinggal sejarahnya saja.' Sora tidak mengatakan apapun atau menuliskan sesuatu terkait hal itu karena kerajaan itu sudah menjadi salah satu saksi yang pernah hidup di zaman kejayaannya hingga hancur tak beraturan saat ini. Namun, ada sesuatu dalam postur Sora yang berubah yang di mana ia bisa merasakan beban tempat itu memiliki tekanan yang sama dan menghantui pikirannya seperti di menara kenangan.

Setelah mereka melewati ggerbang depan itu dan berjalan menuju halaman kosong yang dulunnya tempat patung-patung telah direduksi menjadi sosok yang gagah itu tanpa lengan diukirannya dan wajah patung-patung itu hancur seperti terkena oleh hantaman yang sangat keras hingga membuat patung itu masih tetap berdiri namun wajahnya hancur. Jalanan kerajaan Borreal itu berwarna abu-abu yang bercampur oleh salju seperti sesuatu yang sudah lama terbakar dan hal itu bercampur dengan abu dan tulang yang membuat tanah itu menyerapnya hingga berwarna seperti itu.

Kemudian—

Terdengar suara seperti, bisikan? Namun, yang pastinya itu bukanlah angin dan suara itu semakin jelas dan dengan perlahan mendekat ke arah mereka saat ini dan terdengar seperti gerakan seseorang yang mengendap-endap serta telah mengawasi mereka ketika masuk ke dalam kerajaan Borreal itu. Kaelith merasakan perasaan yang sangat buruk mengenai hal ini dan ia menyiapkan busurnya yang sedari tadi ia bawa di tangannya itu. Sora mencoba memerhatikan dengan seksama ke arah gang gelap yang berada di sampingnya itu dan suara itu terdengar lagi namun lebih jelas saat ini.

Suara itu seperti halnya menyeret sesuatu hingga tterdengar suara percikan besi yang diseret di atas tanah, berderak bagaikan tulan-tulang yang bergerak tanpa daging, dan sepertinya ada juga suara anggota badan yang terlalu panjang untuk tubuh yang terseret dengan batu jalanan karena terlalu tinggi atau panjang. 'Kita tidak sendirian.' Ujar Kaelith dengan suara yang pelan dan waspada apa yang akan datang dari arah gang yang gelap dan kosong itu diperhatikan oleh Sora itu. Tak mau mengulangi kejadian sebelumnya di hutan, Sora menghunuskan pedangnya untuk bersiap-siap akan datangnya. Dari bayang-bayang lorong itu, segerombolan yang tak diketahui wujudnya itu namun bukan segerombolan manusia tentunya itu menunjukkan batang hidungnya dari kegelapan gang-gang itu.

Varnished — yang dulunya manusia namun sekarang hanyalah mayat hidup yang berongga dengan kulitnya seperti kulit kayu terkelupas dan matanya yang bersinar dengan cahaya merah di dalamnya seperti boneka yang dikendalikan oleh seseorang. Rangkaian sendi tulang yang terlihat cukup jelas dan terlihat seperti tertekuk ke arah belakangnya serta mulutnya yang dijahit tertutup rapat dengan kawat besi tipis seperti benang jahit.

Lima Varnished? Tidak, melainkan tujuh di antara mereka saat ini yang muncul dihadapan mereka berdua.

Kaelith dengan cepat melepaskan anak panahnya karena Varnished itu monster yang tak bisa diajak bicara sekalipun dan satu kepala dari Varnished itu tersentak ke belakang. Tetapi dua lagi muncul dari titik buta Sora dan Kaelith itu yang merayap di dinding seperti serangga dan mendarat tepat di belakang mereka saat ini. Sora yang terkejut akan hal itu, bergerak dengan cepat yang pedangnya sudah disiapkan tadi. Pedangnya bertemu dengan daging Varnished yang terlihat membusuk itu dan tebasan pedangnya itu mengenai daging Varnished itu yang terlihat rongga-rongga tulang rusuknya seperti suara pecahan kaca yang rusak terkena hantaman benda keras. Satu Varnished terbelah di bagian dadanya, bagian dalamnya keluar asap dan aroma bau busuk yang baunya itu bukan organ busuk melainkan sesuatu hal lainnya yang lebih buruk dari bau bangkai sekalipun.

Kaelith menggulingkan badannya ke samping ketika salah satu Varnished mencoba menyerangnya dari arah belakangnya itu, berguling ke arah samping yang Varnished itu mencoba meraih Kaelith dengan kuku tangannya seperti cakar itu dan Kaelith langsung mengeluarkan pisau berburunya itu untuk menusukkan ke titik vital Varnished itu dan membuat Varnished itu terkapar di tanah setelah tusukan Kaelith tepat mengenai titik kelemahannya. Banyak yang akan datang, dari arah jendela pemukiman-pemukiman warga, dari gang-gang gelap juga, dan dari kabut yang tebal menuju ke arah kastil Borreal itu.

Salaha satu Varnished berhasil mencapai Sora dan menempel di punggung Sora, mencakar bagian belakangnya itu dan menggigit bagian samping lehernya dengan gigi yang seperti jarum jahit itu. Sora dengan reflek membantingnya ke tanah dengan kekuatannya itu dan ketika varnished itu terkapar di atas tanah, ia langsung menghancurkan kepalanya dengan tumit sepatunya itu. Tapi luka yang Sora dapatkan itu terasa aneh dan letaknya berada di bagian leher yang tergigit tadi.

Kaelith menjerit marah karena busurnya patah menjadi dua sekarang dan dia bertarung hanya dengan pisau berburu dan tinjunya karena para Varnished menyergapnya secara langsung dan Kaelith menahan mereka semampunya ketika jarak di antara mereka terlalu dekat itu dan para Varnished itu menyerang Kaelith dengan buas hingga serangan mereka itu membuat busurnya terbelah menjadi dua hingga senar dari busur itu terputus begitu saja.

'Mereka terus berdatangan!'' Ujar Kaelth dengan nada frustasi dan kesal karena senjatanya itu rusak dan Sora berbalik ke arahnya setelah menebaskan pedangnya ke Varnished yang menghampirinya itu, mata Sora mengamati ke sekitar area yang bisa menjadi tempat perlindungan mereka saat ini dari ancaman para Varnished ini yang tidak ada habisnya. 

Di sana! 

Sora menemukan tempat yang dipenuhi oleh buku-buku yang beberapa diantaranya sudah terbakar dan usang di pintu luarnya dan itu adalah perpustakaan yang sebagian bangunannya runtuh namun pintunya masih utuh dan terlihat bisa menahan gerombolan para Varnished yang berdatangan dari segala arah.

Sora meraih pergelangan tangan Kaelith dan menariknya ke arahnya untuk kabur dari kondisi mereka saat ini. Kaelith merasa bingung dan tidak tahu mengapa, ia tak melepaskan genggamannya itu dari Sora yang menariknya dan kabur dari sana. Mereka berlari dengan cepat melewati reruntuhan, mendorong rak-rak, jasad yang sudah verubah menjadi tengkorak, dan bebatuan di belakang mereka yang juga para Varnished itu mengejar mereka dari belakang. Ketika mereka sudah sampai di dalam perpustakaan itu, Sora menutup pintu perpustakaan itu dengan secepat mungkin dan menguncinya dengan tombak patah hingga menyeret sebuah meja besar yang berada di sampingnya itu untuk menahan pintu perpustakaan itu agar tidak hancur oleh gerombolan Varnished yang mengejar mereka.

Kegelapan menyelimuti ruangan itu serta dobrakan pintu terdengar dengan jelas dari gerombolan Varnished itu yang mencoba paksa masuk ke dalam perpustakaan itu dan tak lama suara dobrakan pintu itu berhenti seketika dan langkah kaki mereka yang berjalan ke arah yang tak mereka ketahui itu. Hanya nafas berat dan gemetar mereka terdengar setelah berlari menjauh dari gerombolan Varnished yang mengejar mereka hingga perpustakaan itu. 

Kaelith mencoba menenangkan dirinya itu dengan mengistirahatkan badannya di salah satu kursi perpustakaan itu dengan tangannya yang berlumuran darah dan rambut pirangnya itu terurai. “…Apa-apaan mahluk itu?” Ujar Kaelith yang nafasnya masih tersenggal-senggal dan mencoba untuk tetap tenang. Sora yang terlihat lelah itu setelah melakukan apapun itu untuk bisa selamat dari ancaman tadi, hanya bisa berlutut karena capek akan rasa sakitnya dan kakinya yang terasa mati rasa. 

Sora merasa ada sesuatu yang aneh menempel di bagian samping lehernya itu yang bekas gigitan dari salah satu Varnished menyerang dari arah belakangnya itu dan Sora menemukan sesuatu dari bekas gigitannya itu lalu menarik dengan hati-hati layaknya benang jahit dan sebagian serpihan-serpihan yang bukan tulang, melainkan sebuah benda seperti jarum bentuknya yang memiliki ukiran seperti pecahan batu yang bercampur dengan kaca. “Seseorang membuatnya, yang berarti ada seseorang mengendalikan gerombolan Varnished tadi.” Ujar Kaelith yang melihat Sora sedang memerhatikan serpihan-serpihan itu.

Mereka ada di dalam hati kerajaan Borreal saat ini dan itu masih terasa berdetak layaknya jantung. Di luar pintu, kesunyian yang setelah pengejaran mereka dari gerombolan Varnished memberikan ancaman yang nyata dan brutal bagi mereka. Namun mereka berdua tahu, kerajaan ini tidak dilupakan oleh orang-orang begitu saja namun mengingat setiap yang melewatinya dan yang melangkahkan kakinya ke dalam kerajaan ini. 

Dan Sora masih berdiam diri di tempatnya itu, darah yang mengalir dari arah lehernya dan cengkeramannya pada gagang pedangnya lebih erat saat ini ketika mengetahui sesuatu ada yang tidak beres dengan hal sebelumnya. Ini baru permulaan bagi mereka yang menapakkan kaki ke dalam kerajaan yang hancur itu dan dihuni oleh para monster yang bersembunyi di dalamnya.

Debu menyaring melalui celah-celah di langit perpustakaan itu, berkilauan seperti abu yang berterbangan dan terperangkap dalam sinar matahari yang perlahan memudar. Keduanya duduk dalam diam, darah Sora telah mengering di sisi lehernya itu di kulitnya. Dia telah membalutnya dengan kain kecil yang dimilikinya dan merobek dari jubahnya sendiri. Rasa sakit itu diam-diam terasa di bawah permukaan kulitnya namun dia tidak bergeming akan hal itu.

Kaelith duduk di seberangnya dengan bersandar di kursi perpustakaan yang ia duduki itu. Matanya sekarang terlihat redup dan lebih lelah daripada rasa takutnya. Busurnya itu, yang dulu merupakan bentuk dari keinginannya saat ini tergeletak patah di sudut ruangan seperti sayap burung yang patah sekarang.

'Tidak berguna, Itu hadiah terakhirku dari ayahku sebelum ia meninggal.' gumamnya, lebih kepada dirinya sendiri, seolah-olah busur itu akan membawa pergi kata-kata itu. Dia membuka kantongnya yang berada di samping pinggulnya itu dan di dalamnya, hanya tersisa pisau berburunya, sebuah botol air yang terisi, dan batu untuk mengasah bilah anak panahnya serta berfungsi juga sebagai pemantik untuk api unggun. Tidak ada makanan dan tidak ada obat sama sekali dalam kantongnya itu.

Ketika Kaelith melihat ke arah busurnya yang ia letakkan di sudut ruangan perpustakaan yang tak jauh dari tempatnya itu, menghampiri senjatanya itu dan tangannya gemetar saat dia mengusap busurnya yang patah itu seakan-akan meratapi suatu hal yang sangat berarti baginya. Sora meraih kantongnya itu dari arah samping ketika ia mengetahui apa yang diinginkan oleh Kaelith itu. Sora mengambil sepotong dendeng usang yang ia simpan sebelumnya dari hasil buruannya kemarin di hutan. 

Tidak banyak yang ia miliki bahkan hampir tidak cukup untuk satu porsi untuk seseorang saja. Namun, ia meletakkannya dengan dibungkus oleh sisa kain yang ia robek sebelumnya itu di samping Kaelith yang masih mengusap busurnya yang telah patah itu lalu melangkah pergi dari arah Kaelith tanpa mengganggunya.

Kaelith mendongakan wajahnya dengan cemberut sembari berkata. “Kau belum makan selama dua hari dari perjalanan yang kita tempuh dan terlebih lagi kau mengalami pendarahan lebih banyak dari seekor serigala yang bertarung di sarang para pemburu. Dan sekarang, kau memberiku potongan dendeng terakhir ini? Apa maksudmu itu?” Sora tidak berkata apa-apa untuk menjawab pertanyaan Kaelith itu. Ia hanya berjalan ke tempatnya lagi dan berdiri di dekat ambang pintu belakang perpustakaan yang ia temukan, pedangnya yang bersarung di pinggulnya saat ini ia genggam gagangnya, dan ketika Sora melihat ke arah Kaelith yang tengah bersandar di dinding belakangnya, ia mencoba berbicara dengan bahasa isyaratnya yang seolah-olah berkata, 'Kau akan lebih membutuhkannya daripada diriku.'

Kaelith menunduk dengan lesu lalu mengambilnya. “Keras kepala sekali, bajingan ini.” Katanya dengan lembut. Waktu berlalu dengan cepat hingga matahari yang bersinar di antara celah-celah perpustakaan yang atapnya beberapa hancur dan sebagiannya masih bisa bertahan sebelum ambruk. Mereka memutuskan untuk melanjutkan perjalanan mereka daripada menetap di dalam perpustakaan itu yang kondisi dan situasi mereka hadapi saat ini tak menentu itu.

Ketika mereka meninggalkan perpustakaan yang sebagian hancur bengunannya itu, warna langit kini yang perlahan berubah warna menjadi  abu-abu besi dan matahari perlahan tenggelam di antara langit itu hingga tidak terlihat lagi wujudnya dan cahayanya. Hanya garis besar menara bergerigi yang menjulang di atas kepala, seperti gigi sesuatu yang kuno yang tengah menunggu untuk menutup mulutnya.

Sambil berjalan keluar dari perpustakaan, Kaelith mengikat sisa-sisa dari patahan busurnya yang rusak itu untuk menjadikannya tongkat dengan bergerigi sebagai senjatanya saat ini, lebih baik daripada tidak memegang senjata sama sekali. Setiap langkahan kakinya itu berjalan dengan hati-hati dan matanya selalu memerhatikan sekitar terutama sudut-sudut tempat yang terdapat bayangan. Sedangkan Sora, kini ia berjalan di bagan paling depan dengan tertatih-tatih, lukanya itu memperlambatnya tapi tidak cukup untuk membuatnya berhenti melanjutkan perjalanannya walau lambat. Setiap langkah adalah kata yang tak terucap seperti halnya keinginan yang tak terpatahkan oleh kondisi apapun bahkan badai menerjangnya.

Setelah mereka keluar dari perpustakaan dan berjalan menuju luar gang yang mereka lewati itu, kini mereka sampai di tempat yang dulunya adalah pasar. Kios-kios yang telah lama dilahap api itu cukup terlihat dari sisa-sisa kain yang telah lama terbakar dan pembusukan dagangan yang masih tersisa di beberapa kios yang sudah bercampur dengan abu dan salju yang menutupinya. Boneka-boneka yang berasal dari toko mainan yang pernah berdiri terbungkus oleh perhiasan maupun aksesoris untuk menarik minta anak-anak untuk membelinya kini telah berdebu dan sebagiannya juga ada yang hangus oleh api serta ada juga kepala boneka-boneka itu dengan sengaja digantikan oleh tengkorak burung dan logam yang sudah lama berkarat sebagai tanda pemujaan atau peringatan yang tidak jelas yang terpampang di sebagian jalan.

Lalu—

Sebuah suara terdengar kembali dan kali ini bukan suara cakar yang sama seperti sebelumnya. Namun suara ini adalah suara langkah kaki dan ini betul-betul seperti suara langkah kaki manusia sungguhan yang lambat, terdengar dengan jelas sekali dan bahkan suara ini terdengar sangat disengaja. Kaelith yang mendengar suara itu langsung berhenti dan menyiapkan tongkat pemukul bergeriginya bila ancaman dari Varnished datang ke arahnya.

Dari arah gang seberang mereka, muncul satu sosok saja. Penmapilannya itu seperti seseorang yang mengenakan balutan perban yang berada di sekitar area kepalnya yang menutupi wajahnya dan tulangnya juga serta wajahnya itu tersembunyi di balik topeng porselen yang sudah retak. Sosok itu tidak berbicara ketika bertemu dengan Sora dan Kaelith yang berhenti di hadapannya yang cukup jauh. Kemudian, sosok itu mengulurkan tangannya bukan dengan damai tetapi sebagai undangan kepada mereka berdua itu untuk mengikutinya ke sebuah tempat yang hendak ia ingin tunjukkan kepada mereka berdua. Setelah itu, ia berbalik arah dan berjalan kembali ke dalam kegelapan gang yang ebrada di ujungnya.

Kaelith yang merasakan sesutau ancaman atas perasaan yang tidak enak ia rasakan itu, langsung memegang dengan erat tongkatnya itu. 'ini sebuah jebakan yang sangat jelas untuk memancing kita ke dalamnya dan terlebih lagi menuju area yang kita sendiri tak ketahui.' Desis Kaelith dengan sigap seperti halnya ia siap untuk memukul musuhnya itu dengan tongkat yang sudah berada di dekat kepalanya itu dan terlihat seperti ingin menbghancurkan kepala musuh mereka bila melancarkan serangan dadakan itu. berbedaa dengan Kaelith yang waspada akan hal itu, Sora hanya diam saja dan terus memperhatikan sosok itu serta menerka-nerka maksud darinya itu. Hingga pada akhirnya, Sora melangkah maju ke depan setelah bertaruh kepada firasatnya setelah memikirkan apa maksud dari sosoki itu dan mulai mengikutinya yang menuju ke arah gang yang gelap itu.

'Kau bercanda, kan?'' Ujar Kaelith yang melihat tindakan Sora yang sangat mudah dibaca itu dan mengira Sora sudah terpancing oleh jebakan murahan yang dilakukan oleh sosok sebelumnya itu. Sora tetap melangkah maju ke depan untuk mengikuti sosok itu membawanya dan menghiraukan ucapan Kaelith sebelumnya untuk memperingatkannya sekali lagi.

Kaelith yang melihat tindakan Sora yang terlanjur nekat itu. mengumpat dengan pelan, 'Bajingan bodoh itu, ia tak tahu itu adalah jebakan murahan yang telah disiapkan untuk kuburan kita, bangsat.' Setelah mengumpat Sora dengan pelan dan rasa frustasinya yang melihat tindakannya yang bodoh itu dengan terpaksa Kaelith mengikutinya dari belakangnya. 'Jika kita mati, aku akan menghantuimu di mana pun kau berada hingga ajalmu menjemput.' Timpal Kaelith yang terdengar seperti sumpah itu kepada Sora bila intuisinya salah dan mengakibatkan mereka berdua tewas karena mengandalkan intuisinya itu.

Gang itu menelan mereka bagai seseorang yang telah menembus awan yang mendung di tengah kegelapan gang itu. Apa yang akan mereka temukan di luar sana nantinya itu, bukanlah tempat perlindungan maupun penyergapan melainkan peninggalan nafas terakhir dari Kerajaan Borreal atau yang bisa disebut warisan kerajaan itu yang selamat dari kehancuran kerajaannya. Sebuah ruangan yang terkubur di bawah kota, tersembunyi dari waktu ke waktu, tempat dari sisa-sisa terakhir yang terlupakan serta masih membisikkan rahasia dalam kegelapan diatas permukaannya itu, dan hal yang berharga untuk terus maju... akan memulai menunjukkan harga yang sebenarnya untuk pertama kalinya dan tidak pernah dilihat oleh seseorangpun yang belum pernah merasakan hal itu sebelumnya dalam kehidupannya.

Udara di tempat itu terasa seperti menebal saat mereka mengikuti sosok bertopeng itu ke dalam bayangan yang mengarah ujung gang paling gelap itu. Cahaya yang tersisa tampak memudar sedikit demi sedikit ketika memasuki gang itu semakin ke dalam, seolah-olah enggan untuk tidak membiarkan cahaya masuk ke dalam kegelapan itu secara perlahan-lahan. Sepatu Sora bergesekan dengan batu bulat licin yang telah lapuk selama bertahun-yahun lamanya setelah zaman kehancuran itu dimulai. Napas Kaelith yang stabil tetapi cengkeramannya erat di sekitar tongkatnya itu menunjukkan kewaspadaan disekitarnya sambil mengamati disekitarnya bila ada pergerakan aneh muncul, ia berjalan di belakang Sora dengan langkah yang hati-hati bukan karena ketakutannya namun karena kurang mempercayai pilihannya tadi. 

Gang itu semakin lama, semakin menyempit hingga terlihat di ujung gang itu terdapat jalan ke tangga spiral dari batu hitam yang mengarah ke bawah menuju sebuah cekungan mirip seperti saluran air di bawah kerajaan. Sosok bertopeng itu tidak menoleh ke arah belakangnya dan ia tetap berjalan hingga masuk ke dalam tangga yang spiral itu. Mereka berdua dengan langkah perlahan dan menjaga jaraj dari sosok itu menuruni anak tangga spiral itu terasa seperti waktu berjalan begitu lambat. 

Ketika mereka mencapai dasarnya setelah menuruni anak tangga yang spiraal itu, ruangan terlihat di depan mereka dan sosok itu masuk ke dalamnya yang ruangan itu memiliki pintu yang sudah rusak, terbuka setengahnya saja di hadapan mereka yang luas, melingkar, dan ruangan itu hidup dengan dengungan yang rendah serta tampaknya berdenyut dengan nafas yang masih dimiliki. Pilar-pilar dari susunan batu kuno itu menahan langit tetap tinggi, terukir dengan ukiran sigil-sigil yang menggeliat lembut di bawah energi yang tak terlihat. Patung-patung berjejer di dinding yang tanpa wajah, tanpa adanya mahkota, dan sebagiannya rusak karena waktu telah berlalu. Di antara ruangan itu, terdapat lentera yang berada di dinding menyala dengan sendirinya ketika mereka baru memasuki ruangan itu dan memperlihatkan sebuah mural yang dilukis dengan warna seperti darah dan emas yang menceritakan sebuah penderitaan dengan masa kejayaannya dulu. 

Kaelith berbisik ke dirinya sendiri ketika memasuki ruangan itu dan melihatnya dengan mata yang tak bisa mempercayai apa yang ia lihat saat ini: 'Ini... ini seperti sebuah singgasana yang tersembunyi di bawah dari singgasana sebuah kerajaan di permukaannya.' Di tengah-tengah ruangannya terpapar sebuah alas permadaani yang sudah usang dan robekan yang sudah termakan oleh zaman dari waktu ke waktu dan di ujung ruangan itu terdapat sebuah etalase yang di sana terdapat sebuah busur yang bukan terbuat dari kayu maupun logam. Tetapi dari urat yang tak diketahui bahannya itu dan bersinar layaknya cahaya bintang sudah ditempa dari sesuatu yang terlupakan.

Sosok bertopeng itu melangkah ke samping dengan perlahan dan berhenti tepat di samping etalase busur itu, menunjuk Kaelith tanpa suara. Melihat hal ini, Kaelith tak tahu apa yang dimaksud oleh sosok tersebut dan ragu-ragu akan hal itu hingga ia menggenggam tongkatnya yang sedari tadi ia pegang di tangannya. 'Kau berharap aku akan... memeberikannya begitu saja kepadamu?' Ujar sosok itu kepada Kaelith dengan menunjuk Kaelith dan suara seraknya yang dingin itu membuat Kaelith semakin tak yakin kepadanya. Tidak ada jawaban dari Kaelith melainkan meningkatkan tingkat kewaspadaannya ketika sosok itu mulai berbicara. Hanya sebuah dengungan perkataan sosok itu dan kehadiran Sora yang tenang di sampingnya.

Busur itu berdenyut samar dari etalase itu dan kenangan yang tersimpan di dalamnya akan seorang pemilik busur sebelumnya itu. 'Kau, pemanah yang telah kehilangan senjatanya. Apa yang membuatmu layak untuk memiliki busur ini? Apakah busur dari seorang pemanah itu berarti bagimu?'' Tanya sosok itu kepada Kaelith dengan menurunkan jarinya yang menunjuk Kaelith sedari tadi. Kaelith yang mendengar pertanyaannya itu menjawab dengan nada yang dingin, 'Aku tidak pernah tahu hal itu. Yang aku ketahui adalah bagaimana cara bertahan hidup di dunia yang sudah hancur ini untuk melihat matahari terbit di keesokan hari yang di mana kehidupan kita sendiri ini tak menentu di dunia yang sudah melupakan harapannya untuk hidup ini.' Mendengar jawaban Kaelith, sosok itu hanya melihat ke arah busur itu sekejap dan melihat kembali ke arah Kaelith. 'Majulah, putri Virandel. Kau mengetahui apa yang diperlukan untuk memiliki busur ini.' Kaelith yang mendengar hal tersebut dari sosok itu tersentak dan mengencangkan genggamannya dengan bingung dan bercampur dengan emosinya saat ini, 'Kau... kau tahu darimana nama itu?' Sosok itu tak memedulikan apa yang dilakukan Kaelith maupun ucapannya melainkan sosok itu berkata 'Kau akan tahu ketika kau mengambil busur ini.' Kaelith tetap berada posisinya itu dengan melihat sosok itu.

Lalu, Kaelith perlahan maju ke depan ketika tahu sosok itu tak bereaksi apapun setelah mengatakan hal tadi dan tidak ada aksi yang mencurigakan juga dari gerakannya. Kaelith melihat busur itu dari dekatnya dan mencoba memegang busur tersebut. Ketika jari-jarinya menyentuh busur itu terlihat kilas balik tak tahu darimana asalnya langsung masuk ke dalam pikiran Kaelith untuk melihat sekilas apa yang terjadi dengan pemilik sebelum busur tersebut. Dalam pikiran Kaelith, terlihat seorang wanita yang rambutnya berwarna seperti api, melepaskan anak panah yang mengubah seluruh yang ia bidik itu menjadi debu, seperti halnya ia menjaga pertahanan yang terakhir sebagai pemanah di atas tembok gerbang Borreal, dan sebuah janji yang tak terucapkan itu muncul dengan suara samar-samar dalam pikiran Kaelith ketika melihat aksi dari seorang wanita tersebut, 'Ini akan menemukan tangan yang dimaksudkan untuknya.'

Kaelith yang melihat semua hal itu tiba-tiba tersentak dan melepaskan sentuhannya dari busur itu secara tiba-tiba. Kaelith berjalan mundur setelah melihat hal itu dengan ekspresi apa yang baru saja ia lihat tadi. 'Apa... apa yang sebenarnya terjadi pada wanita itu dan tempat ini?' Sosok bertopeng itu akhirnya berbicara seperti angin melintasi kuburan. 'Sang pemilik dari busur ini menyegel sebuah kebenaran yang tak pernah diucapkan maupun dilihat oleh satu orangpun. Kerajaan ini runtuh bukan karena sebuah perang saudara atau lainnya melainkan sebuah ancaman dari dalam. Mereka yang melakukan hal itu, minum dari sumur yang bukan milik manusia. Mereka menghancurkan dengan membangunkannya dan hal itu yang seharusnya untuk tetap tertidur. Kejatuhan Borreal... adalah sebuah penebusan dosa bagi mereka.'

Kaelith mencoba tetap tenang dan memahami perkataan sosok itu sebelumnya dengan busur di atas etalase itu yang telah menunjukkan sesuatu terhadap pemilik sebelumnya. Kaelith menoleh ke arah Sora yang tetap tenang ketika melihat kondisi Kaelith seperti itu dan Kaelith kembali melihat ke arah sosok itu dan bertanya. 'Dan mengapa kau membawa kami ke sini?' Sosok itu menoleh ke Sora. 'Karena dialah orang terakhir yang tidak tersentuh oleh kebohongan. Dia lahir tanpa kata-kata yang mereka gunakan untuk membentuk sebuah kebenaran dari tindakannya sebagai kata-kata yang tak pernah diucapkan menjadi rantai yang tak pernah putus akan sebuah kebenaran yang tak ingin didengar oleh banyak orang.'

Sora mendengar hal itu dari sosok itu melangkah lebih dekat ke arah etalase busur itu yang masih berada di tempatnya dan tangannya mulai meraba-raba sesuatu di samping etalase tanpa menyentuh busur itu yang terasa ada sesuatu di sampingnya. Sora menemukan sebuah aksara sigil yang tersembunyi di samping etalase itu yang aksara itu terlihat dengan samar. Saat Sora menyentuhnya, dinding ruangan sebelah etalase itu bergeser ke arah samping, memperlihatkan sebuah peta luas yang hampir tak bisa dibaca tulisannya dan gambarnya di batu, memperlihatkan wilayah yang telah lama hilang, dan sebuah tanda di dalam bawah tanah yang di mana sebuah tempat para pendosa Borreal masih tertidur untuk dibangunkan.

Sosok bertopeng itu berbisik kepada mereka berdua dengan nada seraknya: 'Kau tidak ditakdirkan untuk menyelamatkan dunia. Tapi kau dapat memilih siapa yang akan membangunnya kembali.' Dan dengan perkataannya itu, sosok itu melangkah mundur ke dalam sudut ruangan yang gelap dan menghilang diantara bayangannya. Kaelith menatap Sora dengan seksama. 'Jadi... tidak ada tekanan kalau begitu.' Sora hanya tersenyum pahit samar ketika mendnegar hal itu sambil melihat ke arah peta batu itu dan ada sebuah pintu di samping dinding peta itu. Ekspresi wajahnya itu hampir tidak terlihat.

Lalu, tanpa sepatah kata pun, mereka melihat pintu yang berada di samping sebuah peta batu itu dan Jalan ke arahnya kini dan tujuan mereka yang tak pernah mereka mau dan diinginkan oleh sosok itu kini lebih jelas... tapi bebannya lebih berat untuk sebuah tujuan bagi mereka. Kerajaan yang hancur telah memberi mereka sebuah senjata dan bisikan tentang kebenarannya. Apa yang terbentang di baliknya, lebih dalam ke tanah yang sudah tak ditumbuhi oleh tanaman-tanaman maupun rumput dan hal ini bukan lagi sekadar bertahan hidup. Itu adalah sebuah perhitungan yang mereka harus pikirkan terlebih dahulu sebelum melangkah ke depan.

Ruangan itu kembali sunyi setelah sosok itu menghilang. Kaelith duduk di dekat etalase busur yang ditempatkan itu, busur barunya telah diambil olehnya dan kini berada di pangkuannya. Cahaya redupnya itu menandakan busur itu saat ini tertidur sampai dipanggil untuk digunakan. Satu-satunya suara tersisa di ruangan itu adalah tetesan air yang lambat dan bergema dari celah-celah di atas langit-langit ruangan itu dan langkah kaki Sora yang pelan saat ia melangkah di tepi ruangan untuk menganalisis peta batu yang berada di depannya saat ini.

Keheningan di antara mereka tidaklah hampa. Kaelith memperhatikan Sora seperti orang asing yang diam telah berjalan melewati kengerian dan kenangan tanpa mengucapkan sepatah katapun untuk menjelaskan kondisinya. Ia tidak pernah bergidik, ia tidak pernah memohon, dan ia tidak pernah mempertanyakan alasannya mengapa dan untuk apa.

'Kau telah melihat lebih dari yang kebanyakan orang bicarakan dalam mimpi.' Kata Kaelith kepada Sora yang akhirnya memecah keheningan mereka berdua di dalam ruangan itu. Tidak ada jawaban dari Sora melainkan hanya kedipan mata Sora yang bertemu dengan matanya ketika mendnegar perkataan Kaelith itu. Tak mau terasa canggung, Kaelith meraih kantongnya dan mengambil sepotong kecil dendeng yang diberikan Sora sebelumnya itu. Kaelith melemparkan  dendeng ke arah Sora dan Sora menangkapnya dengan mudah. 'Makanlah, pahlawan bisu. Aku tidak akan menyeret mayatmu jika kau jatuh nantinya.'

Sora hanya mengangguk sedikit dan memakan apa yang telah diberikannya walau tahu bahwa dendeng itu darinya sebelumnya itu. Kaelith mendesah yang terasa seperti tak tahu apa yang harus ia lakukan, sambil melihat ke atas langit ruangan itu. “Dunia ini... dulunya memiliki sebuah arti. Kerajaan Borreal... bukan hanya sekedar kerajaan. Dulunya kerajaan ini adalah satu-satunya kerajaan yang merupakan mercusuar atau lebih tepatnya sebuah rumah bagi para penduduknya. Lalu sesuatu telah berubah ketika dunia menemukan kehancurannya, salah satunya tempat tinggalku dulu yang hancur karena sesuatu yang berasal dari bawah batu dan tanah. Tiba-tiba kita bukan lagi seorang manusia hidup dengan tenang melainkan kita berubah menjadi sesuatu yang tak bisa aku sebut dan mulai untuk memikirkan keselamatan diri sendiri dibandingkan keluarga terdekat manapun.” Suara Kaelith terasa sedikit bergetar ketika akhirnya menceritakan sesuatu yang tak mau ia ceritakan kepada siapapun itu. Dia berdiri, mencengkeram busurnya itu lebih erat. “Kau tidak tahu bagaimana rasanya berteriak, bukan? Dan tidak ada yang mendengarmu ketika kau melihat semuanya membusuk dan diminta untuk tetap tersenyum untuk melewatinya?”

Kaelith menoleh ke arah Sora dan berkata lagi. “Tapi aku pikir... mungkin kau tahu hal itu dan itulah alasanmu terus berjalan dengan setiap beban yang tak pernah kau ucapkan, bukan?” Sora yang mendnegar hal itu, tidak bisa mengatakan apa-apa selain melangkah lebih dekat ke arah Kaelith. Dan dengan perlahan, ia meletakkan tangan Kaelith di dadanya. Kaelith yang merasa terkejut dengan tindakan Sora ini merasa sesuatu yang aneh dari lubuk hatinya yang terdalam. Sora melakukan hal itu bukan untuk mencoba mendekatkan dirinya kepada Kaelith melainkan hal itu sebagai sebuah isyarat yang ingin ia katakan namun ia tak bisa mengucapkannya, sebuah janji yang ia buat namun tak pernah terdengar oleh siapapun, dan tanpa adanya kata-kata selain pengertian seseorang akan dirinya itu.

Kaelith hanya tertunduk melihat isyarat itu setelah melihat tindakan Sora itu ke arah wajahnya saat ini. Dan untuk pertama kalinya, sesuatu di mata Kaelith melihat sisi kelembutan yang dimiliki Sora sebagai seorang manusia. Kaelith yang terasa terlena akan hal itu, langsung mengalihkan pandangannya ketika jantungnya mulai berdegup dengan cepat dan ia melangkah ke depan ke arah pintu sebelah dinding peta batu itu dan berkata kepada Sora dengan nada yang merasa canggung dan pelan. 'Kita akan masuk ke dalam gerbang itu setelah ini, Apakah kau sudah siap? Dan mungkin...' katanya, suaranya kini lebih tenang namun Kaelith terdiam ketika hendak ingin melanjutkan perkataannya yang terputus itu. Mereka berdua mengetahui hal itu bukan sekadar mungkin melainkan sebuah ujian untuk mengetahui kebenaran secara detail melalui mata mereka untuk melihat apa yang sebenarnya di balik pintu ini sembunyikan hingga tak ada yang mau membicarakan tentang sebuah kebenaran yang terpendam cukup lama itu.";

                $paragraf = preg_split('/(\r\n|\n|\r){2,}/', $naskahLengkap);
                $naskahTerformat = '';
                foreach ($paragraf as $p) {
                    if (!empty(trim($p))) {
                        $naskahTerformat .= "<p>" . trim(nl2br($p)) . "</p>";
                    }
                }
            @endphp

            <div style="font-size: 1.1rem; line-height: 1.8;">
                {!! $naskahTerformat !!}
            </div>

            <hr class="my-5">

            <div class="d-flex justify-content-center flex-warp gap-3">
                <a href="/story/the-unkindled/bab-dua" class="btn btn-lg btn-contrast">Kembali ke Bab Sebelumnya</a>
                <a href="/story/the-unkindled/bab-empat" class="btn btn-lg btn-contrast">Lanjut ke bab berikutnya</a>
                <a href="/story/the-unkindled" class="btn btn-lg btn-contrast">Kembali ke Halaman Novel</a>
            </div>

        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    document.cookie = "lastRead_the-unkindled=bab-tiga; path=/; max-age=31536000; SameSite=Lax";
</script>
@endpush