@extends('layouts.app')

@section('title', 'Bab Empat - The Unkindled')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            
            <h2 class="text-center mb-4">Bab Empat: Mahkota Mayat Hidup</h2>
            <hr class="my-4">

            @php
                $naskahLengkap = "Mereka meninggalkan ruangan itu dalam keadaan diam dan penuh keheningan setelah memasuki pintu yang mengarah ke suatu tempat yang tak bisa dikatakan tempat bersejarah melainkan sebuah kuburan yang telah digali untuk mereka dan udara di dalam tempat itu menjadi lebih dingin dibandingkan oleh ruangannya yang sebelumnya. Kota Borreal yang hancur dari atas terasa getaran di bawah kaki mereka seolah merasakan apa yang menggetarkan hati mereka melihat tempat yang sudah hancur, hanya tanah gersang di sepanjang mata mereka memandang, dan erlihat banyak kuburan di tempat itu serta sebuah katedral yang tampaknya masih berusaha tidak hancur walau sebagiannya sudah rusak parah dengan sebuah bel yang masih menggantung di atasnya.

Saat mereka melewati pintu tadi, angin menderu sangat kencang dan berdesis seperti serigala yang tertawa kecil. Tiba-tiba, makhluk-makhluk yang lebih mengerikan daripada Varnished bangkit dari celah bawah tanah kuburannya, dagingnya berurat berwarna hitam, tulangnya menyatu dengan baju besi berkarat serta ada dagingnya itu menyatu dengan akar-akar tumbuhan yang sudah lama mati, dan puluhan wajah makhluk itu terlihat berlubang serta mencekung ke arah dalam dan sebagian wajah mereka sudah terjahit oleh sesuatu seperti benang yang dijahit di bagian punggungnya. Di wajah mereka yang wajahnya dijahit di bagian punggungnya itu, matanya mengeluarkan darah dari jasadnya seperti menangisi sesuatu yang seharusnya tak mereka lakukan namun sudah terlamabta untuk itu semua. Jeritan mereka yang seperti memecahkan gendang telinga bagi siapapun yang mendengarkannya.

Kaelith dengan sigap, menyiapkan busurnya lalu berkata. “Itu bukan sekedar binatang buas. Melainkan yang sudah mati dipaksa untuk hidup kembali walau enggan untuk bangkit lagi.” Sora melihat serupa apa yang dilihat oleh Kaelith, langsung menghunuskan pedangnya dan mempersiapkan ancang-ancangnya dan matanya terpaku pada satu hal apa yang menarik perhatiannya ketika sampai di tempat itu.

Ini bukan pelindung dari yang telah mengorbankan jiwanya untuk mempertahankan kerajaan Borreal yang sebelumnya runtuh itu melainkan para pembangkang dari kerajaan Borreal yang diberi hukuman oleh seseorang untuk mengerjakan tugasnya kembali ketika tempat mereka terancam oleh sesuatu. Dari bayangan di atas katedral tepat di tempat lonceng itu berada, terdapat sosok yang tertawa dengan nada ancaman begitu bergema disekitar penjuru tempat itu yang hampa dan memiliki niatan tersembunyi.

Sosok muncul di atas katedral itu dengan jubah yang sudah lama terkoyak dan berawarna seperti abu. Topeng porselen yang retak berbentuk senyuman yang terjahit seperti memberikan ancaman yang sangat nyata untuk mimpi buruk seseorang yang membangkang darinya. “Kalian menemukan ruangan itu, bukan?” desis sosok itu kepada Sora dan Kaelith sebagai ucapan selamat datang yang mengancam dengan nada yang terdengar seringai diiringi nada yang serak dan berat namun terlihat senang atas apa yang ditemukan oleh Sora dan Kaelith itu. “Apakah ruangan itu membisikkan sebuah kebenaran yang manis? Apakah ruangan itu menawarkan sebuah harapan yang kami inginkan? Kalian pikir para dewa menghukum kerajaan Borreal? Tidak… melainkan kami memohonnya untuk tetap seperti ini.” Tambah sosok itu dengan nada yang berubah seperti bisa ular yang mencoba menarik perhatian lawannya. Kilat hitam membelah langit merah di tempat itu. Pasukan mayat hidup yang tellah dibangkitkan itu, berjalan perlahan ke arah mereka berdua untuk menerjang mereka.

Kerajaan yang hancur itu sekarang akan mengatakan kebenarannya… dengan darah. Jalanan Borreal kembali terbakar dan dipenuhi oleh darah sekali lagi. Bukan dengan api untuk membakarnya melainkan dengan pertumpahan darah bagi pasukan mayat hidup itu sebagai himne mereka dan benturan pedang mereka yang berkarat mengenai batu dan baja sebagai bentuk teriakan perang untuk mereka.

Melihat kondisi seperti ini sudah tak bisa untuk diajak berdiskusi sehat maupun diberi sebuah sarkasme untuk menghindari pertarungan yang tak imbang itu, Kaelith dengan cepat melepaskan anak panahnya dengan presisi yang dahsyat dan setiap anak panahnya itu seperti mengeluarkan teriakan dari jiwanya dan jiwa busur itu sendiri. Sedangkan Sora bergerak seperti hantu di tengah kekacauan, tidak ada teriakan perang terdengar dari mulutnya, tidak ada suara yang keluar pula dari mulutnya, melainkan tebasan pedangnya saja yang bernyanyi seperti angin di kuburan sebagai melodi untuk yang telah mati diistirahatkan kembali ke tempat tidurnya sebagai lagu pengantar tidur mereka.

Namun, jumlah pasukan mayat hidup itu lebih banyak dan terus bermunculan dari bawah tanah. Sepuluh banding satu. Tidak, bahkan lebih dari itu untuk memperhitungkan perbandingannya. Pasukan mayat hidup itu yang memiliki bentuk tak dapat dikenali, keluar dari katedral yang hancur seperti singa yang baru saja keluar dari kandnagnya di tengah-tengah pertunjukan sirkus sebagai acara utamanya. Beberapa dari mereka adalah raksasa yang berpakaian zirah besi raksasa layaknya prajurit kerajaan dan yang lainnya merangkak dengan keempat kakinya bagai sekumpulan hyena menunjukkan taring gigi mereka yang panjang dan terlihat tajam dan mata mereka melihat ke arah Sora dan Kaelith sebagai mangsa empuk mereka hari ini. Mereka adalah gema kerajaan yang terlahir dari dosa-dosanya sendiri.

Kaelith yang sednag melepaskan anak panahnya dan mencoba ke arah pilar yang sudah runtuh namun sisa reruntuhan memberikan penglihatan dari atas untuk posisi yang pas menembakkan anak panahnya. Kaelith berlari dengan kencang dan cepat serta menghindari beberapa serangan dari pasukan mayat hidup itu. Tiba- tiba, sebuah serangan meluncur dari arah pasukan mayat hidup itu hingga Kaelith mengeram saat sebuah tombak terlihat menyerempet arah bahunya yang tak bisa diprediksi pergerakan serangan pasukan mayat hidup itu. Busurnya hampir mengenai serangan itu juga, tetapi tidak ada tanda-tanda kerusakan berarti dari serangan itu. Kaelith berguling ke arah sampingnya dan menembakkan anak panahnya tepat ke mata mayat hidup yang mencoba membunuhnya itu dengan tombaknya.

Namun semakin mereka berdua berusaha untuk melawan pasukan mayat hidup itu, semakin lebih banyak lagi yang datang dari bawah tanah untuk menghadapi mereka berdua dan menggantikan yang sudah dikalahkan oleh mereka berdua.

Dan Sora… Dia mengalami banyak pendarahan setelah bertarung dengan segerombolan pasukan mayat hidup itu dengan jarak yang dekat dan membiarkan setiap serangan yang dilancarkan mereka itu mengenainya namun Sora tidak kehilangan fokus melainkan memberikan seraangan balik yang sangat hebat hingga menumbangkan beberapa dari mereka itu. Saat Sora masih bertarung dengan pasukan mayat hidup itu, tanpa ia sadari saat ini ia terpojok yang dengan sengaja pasukan mayat hidup itu memisahkan Sora dengan Kaelith hinga membuat salah satu dari mereka terpojok oleh mereka yang lebih banyak itu. 

Ketika Sora sudah terpojok dan dibelakangnya hanya ada sebuah dinding besar yang sudah runtuh itu membuat pergerakannya semakin minim dan tidak leluasa ketika sudah dikerubungi pasukan mayat hidup yang mengelilinginya. Tiba-tiba, seorang ksatria mayat hidup dengan zirah dan pedangnnya yang patah serta berkarat datang dan jauh dua kali lebih besar dan kuat dari Sora. Pedang berkarat ksatria itu menusuk sisi badannya dan darah yang berwarna gelap keluar dari dalamnya akan sebuah kutukan yang sudah terselimuti dnegan pedang berkarat ksatria itu. Sora mencoba memukul mundur ksatria mayat hidup itu dan bangkit dari serangan yang terkutuk itu namun ksatria itu menusukkan bilahnya lagi lebih dalam ke arah dadanya dan tidak memberikannya kesempatan untuk melawan.

Kaelith yang terpojok juga itu, sempat melihat ke arah Sora yang terlihat sudah dihabisi oleh gerombolan pasukan mayat hidup itu, menjeritkan namanya. 'Sora!' Kaelith mencoba sekuat tenaganya untuk membukakan jalannya ke arah Sora untuk membantunya tetapi segerombolan mayat hidup itu mengepungnya dan tak membiarkan sedikit celah baginya untuk pergi ke arah Sora yang sudah direncanakan oleh mereka. Kaelith yang menyadari sudah betul-betul terkepung saat ini oleh gerombolan mayat hidup itu mengelilinginya dan mneyerangnya dengan brutal. Kaelith terpaksa mundur dengan perlahan sambil menembakkan anak panhnya hingga habis dan Kaelith hanya bisa tersenyum pahit ketika mengetahui tidak ada lagi anak panah yang tersisa dimilikinya dan akhirnya yang tersisa darinya itu hanya melawan gerombolan itu dengan tongkat yang ia buat sebelumnya itu hingga waktu ajalnya tak terelakkan lagi.

Namun—

Di tengah kondisi yang sangat berat sebelah dan serangan-serangan brutal yang mereka dapatkan itu berubah sangat drastis ketika tangan Sora memegangi pedang berkarat yang ditusukkan oleh ksatria mayat hidup di bagian dadanya itu. Dengungan yang lirih berdenyut dari jantung Sora seperti sesuatu yang telah bangkit namun itu tak seharusnya terbangun. Seketika cengkeraman tangan Sora menguat kembali dan mencoba melepaskan dari tusukan pedang yang menembus dadanya itu. Ksatria itu tentunya dengan kekuatannya mencoba menusukkan kembali ke dada Sora dengan sekuat tenaga namun Sora berhasil melepaskan tusukan pednagnnya itu dan membuang pedang ksatria itu jauh dibelakangnya. Perawakan Sora saat ini seperti sebuah simbol yang telah lama memudar dan kini membakar kembali ke dirinya sendiri dari dalam dalam dadanya sebagai sumbernya. Sebuah cahaya api yang terbakar seperti sigil yang telah membara dan bersinar berwarna merah seperti bara api.

Matanya terbuka dengan lebar yang bukan karena luka yang ia dapat tetapi karena kekuatan yang telah bangkit itu sudah mengalir di setiap darahnya dan seperti mendapatkan tusukan adrenalin yang sangat hebat. Dia menggenggam pedangnya yang tergeletak… dan mulai menebaskan ke arah ksatria mayat hidup itu tanpa memberikan peluang baginya untuk menyerang. Ksatria mayat hidup itu terhuyung mundur akan serangan Sora lakukan dengan tak memberikan sepersekian detik untuk menyerang melainkan bertahan dan melihat dirinya terus menerus terkena tebasannya. Dalam satu gerakan, Sora tidak kehilangan kesempatan ini ia meluncur seperti elang menyergap mangsanya dengan pedang di tangannya dan jubahnya yang sebagian terkoyak akan serangan yang didapatnya seperti bayangan yang terbakar.

Sora bergerak dengan cepat seperti halilintar yang belum pernah dilihat siapapun sebelumnya. Ksatria itu mencoba menyerangnya dalam keadaan bertahan itu untuk membalikkan serangannya namun Sora menghilang di hadapannya dan seketika Sora muncul kembali di belakangnya. Pedangnya mengiris tulang belakang ksatria itu dalam satu tebasan lengkungan yang sangat bersih yang membuat ksatria itu beristirahat lagi setelah kebangkitannya menjadi mayat hidup digerakan oleh sosok itu.

Kemudian Sora berbalik ke arah pasukan mayat hidup itu dan menerjang ke arah mereka yang mencoba mengepung dan menghabisinya. Kaelith yang sedari tadi mencoba bisa bertahan dari serangan gerombolan itu melihat sesuatu yang tidak wajar ditengah gerombolan-gerombolan mayat hidup itu seolah-olah ada yang membukakan celah di tengah-tengah gerombolan itu. ia memerhatikannya selama ia bisa sambil menghindari beberapa serangan yang datang kke arahnya itu dan ia menemukan Sora dengan wujud tak biasa itu mulai mengobrak-abrik gerombolan mayat hidup itu dengan tebasan pedangnya yang semakin brutal dan cepat. Kaelith hanya bisa membeku melihat kejadian itu dengan matanya terbelalak. 'Apa... yang kau...?' Gumam Kaelith ketika berusaha fokus terhadap pertarungan didepannya itu dan mencoba memahami siapa Sora sebenarnya itu dengan ia melihat kejadian seperti itu.

Sora masih menebaskan pedangnya hingga membukakan jalan bagi Kaelith untuk keluar dari kepungan mayat hidup itu. Sora berlari menghampirinya untuk membantu Kaelith dalam keadaan hampir putus asa dengan menggunakan tongkat bergeriginya melawan mereka. Ketika kondisi mereka saat ini menguntungkan untuk menyerbu lusinan mayat hidup itu terus bermunculan dihadapan mereka sekaligus dengan pedang yang digenggam Sora, ia menebas mereka seperti menuai gandum yang sudah matang dan siap dipanen saat ini. Lengkungan pedangnya yang berwarna merah seperti bara api yang membakar setiap tebasannya ke arah musuhnya. Anggota tubuh mayat hidup itu berserakan di atas tanah kering dan rusak itu disertai juga dengan baju zirah dari ksatria-ksatria mayat hidup juga. Tulang-tulang mayat hidup yang terkena tebasan sora itu berderak seakan-akan suara itu seperti Sora sedang menebang pohon yang hanya bisa ia robohkan dalam sekali pukulannya.

Seekor binatang mayat hidup mencoba menerjang Sora dengan taringnya berwaran gelap yang sudah dipenuhi dengan kutukan itu. Namun, Sora menangkap rahangnya dengan mudah dan menghancurkannya dengan tangan kosong hingga tak bersisa dan melemparkan bangkainya ke kerumunan pasukan mayat hidup itu. Darah yang berwarna gelap, membasahi batu-batu sekitarnya.

Kaelith melihat sebuah peluang yang dilakukan oleh Sora yang berhasil bangkit dan kembali memasuki ke dalam medan perang, semangatnya terbakar layaknya alunan musik yang tak beraturan dan ketika disekitar pasukan mayat hidup itu sudah tak ada lagi, Kaleith dengan cepat mengumpulkan sisa anak panahnya itu dari mayat hidup itu baik dari anak panah yang ia lesatkan dan sisa anak panah yang sudah usang menancap itu. terkumpul sekitar 50 anak panah yang berhasil ia dapatkan dan Kaelith bergerak menuju Sora dengan menghemat sisa anak panahnya itu dengan menggunakan tongkatnya untuk melindungi dirinya. Mereka berdua seperti badai yang mengamuk ketika bertarung berdampingan, yang satu diam dan yang satu lagi terus memukulkan tongkat bergerigi yang dibuatnya untuk membuka jalan ke arah katedral itu.

Tapi kemudian—

Sebuah lonceng berdentang cukup keras dari arah katedral yang nadanya lirih menggema di sekitar tempat itu dan sebuah tanda yang akan buruk terjadi dekat-dekat ini. Pasukan mayat hidup itu berhenti seketika dan berbalik ke arah katedral. Dan menariknya lagi, ketika lonceng itu berbunyi, mereka semua berhenti tidak melakukan apapun melainkan berjalan ke arah katedral yang berada dibelakangnya. Ketika pasukan mayat hidup itu berada di depan katedral, mereka membentuk sebuah lingkaran yang terlihat sebagai arena dengan tembok para mayat hidup untuk sebuah pertarungan intensif yang akan terjadi. Sosok yang menggerakan mayat hidup itu, turun dari puncak katedral meluncur turun ke bawah seperti abu. Diselimuti menara tulang yang telah dibuat oleh mayat-mayat hidup yang ia gerakan dan dimahkotai dengan tulang dan daging yang membentuk lingkaran dengan sisa-sisa darah gelap mayat hidup itu.

Sosok itu memiliki penampilan dengan topeng yang mengagambarka mulut yang sedang tersenyum disertai jahitan-jahitannya di setiapnya dan mengangkat tangannya untuk memanggil tongkat sihirnya yang dari akar pohon sudah mati daan ada sebuah bola sihir yang berwarna hitam diujungnya itu. “Sekarang... mari kita lihat apa yang telah kau temukan dari kebenaran yang kalian lihat sebelumnya.” Setelah mengatakan hal itu, ia lenyap ke dalam asap yang dibuatnya di sekitar arena depan katedral itu. Sosok itu telah tiba bukan sebagai ujian bagi mereka melainkan sosok yang terlihat menyimpang dari apa yang pernah ia pelajari hingga ia menjadi seorang raja dari mayat hidup yang ia kendalikan saat ini dan sebuah mimpi buruk yang sebenarnya... baru saja dimulai.

Gerbang katedral yang berada dibelakang sosok itu, berderit terbuka perlahan yang mengeluarkan deruan angin yang dingin dan tidak mengenakan seolah-olah oleh tangan dari sosok itu memanggil atau meminta sebuah kekuatan untuk melawan Sora dan Kaelith yang sudah berada dihadapannya dan sosok itu melangkah maju, wujudnya berubah seperti asap dengan jubah yang ia kenakan dibuat dari kulit-kulit yang sudah mati dan membusuk.

Tongkatnya bersinar karena bola sihirnya itu kini memancarkan cahaya hitam yang sangat gelap dan sepertinya bola sihir itu terbuat dari sebuah batu yang terkutuk dan di dalamnya itu terlihat daging-daging mayat hidup, ujung tongkat kayunya itu menggesek bebatuan dan tanah di sekitarnya, dan meninggalkan jejak rune yang terbakar oleh api kegelapan sosok itu. Di sekelilingnya, udara terasa aneh tebal, berat, berbau busuk dan jeritan dari setiap jiwa yang telah terikat olehnya menjadi pasukan mayat hidupnya.

Sebuah suara serak keluar dari balik topengnya. “Kau datang untuk mengungkap apa yang hilang dari kerajaan ini. Biarkan aku menawarkanmu... untuk memberitahu semua yang kuketahui.” Dia membantingkan ujung tongkatnya ke tanah dan langit yang sebelumnya berwarna merah bercampur dengan ungu itu sepenuhnya berubah menjadi hitam dan gelap tanpa adanya awan, bintang, dan bahkan bulan sekalipun sebagai pancaran sinar cahayanya.

Katedral itu terlihat saat ini dalam bentuk aslinya yang berwarna merah darah ketika sihir dari sosok yang mengendalikan pasukan mayat hidup itu dan dari tanah dan batu sekitarnya bangkitlah mayat-mayat hidup yang jauh lebih kuat dari sebelumnya yang Sora dan Kaelith hadapi.

Jumlah mereka bukan puluhan saat ini! melainkan ratusan mayat hidup telah bangkit dari tanah kematian. Pria, wanita, prajurit, perwira kerajaan, biarawan, bahkan anak-anak sekalipun sosok itu bangkitkan. Wajah mereka yang dibangkitkan itu tampak terkoyak oleh waktu, tangan mereka masih mencengkeram senjata atau tulang mereka dan mulut mereka terbuka sepenuhnya seperti melihat mangsa yang sangat menggiurkan mereka. Mereka menyiapkan kuda-kudanya lalu menyerang Sora dan Kaelith yang ada dihadapan mereka saat ini.

Sora hanya berdiri diam dan memerhatikan segerombolan menuju ke arahnya namun ia tak melakukan pergerakan tergesa-gesa melainkan berjalan pelan ke arah mereka yang menghampiri dirinya dengan pedangnya yang sudah disiapkan di sisinya lalu bergerak cepat ke arah mereka ketika sudah mencapai jangkauan serangannya itu.

Kaelith menggertakkan giginya ketika melihat tindakan Sora sudah berada di luar akal sehat untuk dicermati lagi karena ia bukanlah manusia biasa seperti yang ia bayangkan dan terdapat rasa menyesal dengan pertemuan pertamanya dengannya itu menghantui di benaknya saat ini ketika melihat kekuatan sesungguhnya dari Sora itu. “Tidak ada jalan keluar dari pertarungan ini. Tidak bila tanpa sebuah rencana. Namun, hal itu sia-sia saja kalau keadaannya sudah seperti ini.” Ujar Kaelith dengan pelan dan menyiapkan busurnya kembali dan menaruh anak panahnya di busurnya itu untuk membidik dengan keakuratan dan intuisi yang tinggi selagi ia hanya mempunyai 50 anak panah tersisa yang dimilikinya saat ini.

Kaelith bergerak dengan cepat ke arah samping untuk menemukan spot yang tepat untuk melepaskan anak panahnya. Ketika ia sampai di sebuah bangunan yang terlihat runtuh namun memiliki spot yang bagus untuk memanah, Kaelith langsung melesatkan anak panahnya yang ia temukan dari sisa-sisa dari mayat hidup tadi dan Kaelith juga berusaha melesatkan anak panahnya ke sosok itu namun terhalang oleh gerombolan mayat hidup yang dipanggil oleh sosok itu. Sora tidak menatap sosok itu, ia hanya menatap di depannya saat ini yang menghadapi terdiri dari gerombolan mayat hidup dipanggil dari tanah itu yang jauh lebih kuat dari sebelumnya yang ia hadapi tadi.

Kemudian—

Setelah lama Sora bertarung dan masih belum bisa mencapai tempat sosok yang mengatur mayat hidup dan dihadang oleh para mayat hidup yang dibangkitkannya, Sora melihat ada hal yang sangat janggal ketika melihat ke arah lonceng katedral itu. ingin mencoba hal tersebut, Sora langsung mundur kembali untuk memberitahu Kaelith yang sedang menembakkan anak panahnya itu. Sora membersihkan jalan dan para mayat hidup disekitarnya dan ketika semuanya sudah habis, jari Sora menunjukkan sesuatu untuk memberitahu Kaelith dan hal itu membuat Kaelith memerhatikan apa yang ditunjuk jarinya. Sora menunjuk ke arah lonceng yang tergantung di atas katedral itu. Kaelith yang awalnya bingung dan mencoba mencerna maksud dari arahan Sora lalu ia menyadari sesuatu ketika sosok itu kembali mencoba menghidupkan para mayat hidupnya dan lonceng katedral baru saja berdentang lagi dan membuat Kaelith berkedip ketika melihat hal itu dan menoleh ke arah Sora. “Mengganggu pemanggilannya dengan lonceng…?”

Sora yang mendengar pertanyaan Kaelith itu langsung mengangguk namun sosok itu bergerak lebih cepat untuk membangkitkan pasukan mayat hidupnya. Sosok itu melantunkan mantra pemanggilan lagi ketika lonceng katedral jkembali bergema, lidahnya  yang mengucapkan mantra itu terlihat terbelah menjadi tiga bagian dan melepaskan sebuah kutukan yang menggelapkan batu di bawah kaki mereka yaitu tangan-tangan dari para mayat hidup. Tangan yang merambat seperti tanaman melilit di kaki mereka. Kutukan yang mencoba menyerap jiwa seseorang yang masih hidup, mengunci pergerakkannya, dan menarik mereka ke dalam tanah seerti pasir hisap.

Kaelith yang pertama terkena kutukan dari sosok itu dan merasa dirinya seperti kehidupannya terkuras perlahan-lahan.  “A—aku tidak bisa bergerak!”

Sora yang melihat kondisi Kaelith itu, langsung mendongak ke arah lonceng itu dan ia melemparkan pedangnya langsung ke arah lonceng katedral dengan sekuat tenaga. Lonceng itu langsung berdentang dengan keras ketika berhantaman dengan pedang Sora yang dilemparkannya tadi. Mantra kutukan itu goyah seketika dan para mayat hidup yang dibangkitkan sosok itu menjerit karena suara lonceng itu terikat oleh pikiran mereka. Beberapa dari mayat hidup itu jatuh ke tanah di tengah pertarungan karena terlalu lemah pikirannya dan sebagian yang lainnya pergerakannya melambat karena mencoba untuk bertahan dari suara lonceng itu.

Kaelith terengah-engah ketika tangan yang merambat ke kakinya dari bawah tanah itu kembali ke dalam tanah dan mengerti apa yang dimaksud oleh Sora saat ini. 'Bajingan yang pintar dan pendiam.' Namun, sosok itu tidak berhenti untuk melanjutkan aksinya untuk mengahabisi mereka itu dengan melantunkan mantranya sekali lagi yang menggema. Dia mengangkat tongkatnya dan membuat sebuah bola api hitam yang telah ia panggil dengan sihirnya itu, seperti cahaya kegelapan dari orang-orang yang terkutuk. Sosok itu melemparkannya ke arah Kaelith yang sedang lengah dan baru saja terlepas dari kutukannya tadi. Melihat hal itu, Sora dengan cepat dan mempunyai waktu untuk melakukan sesuatu dengan serangan bola api hitam dari sosok itu dan melompat ke depan Kaelith untuk menahannya dari api yang pada akhirnya meledak ke dirinya.

Sora terhempas ke belakangnya yang hampir mengenai Kaelith, asap mengepul dari seluruh badannya hingga jubahnya, bajunya terbakar oleh api hitam itu di kulitnya dan Sora menggeliat di atas tanah kesakitan tanpa ada suara yang dikeluarkan. Kaelith yang melihat hal tersebut di depan matanya frustasi dan amarah yang berkecamuk akan sosok itu di dalam matanya. 'Kalau begitu aku akan berteriak untuk kita berdua saat ini.' Kaelith dengan sigap langsung menarik busurnya itu yang diberikan oleh sosok sebelumnya dari ruangan sebelumnya itu kepadanya. Busur itu kini berkilauan dengan cahaya perak yang terikat oleh benang-benang ingatan akan semangat dari pemilik sebelumnya.

Kaelith membidik ke arah sosok itu namun sosok itu hanya tertawa tertawa dan memanggil kembali mayat hidup dari bawah tanah yang berada di dekatnya dan dijadikan sebagai perisai baginya. 'Kau pikir kau punya kekuatan? Kau bukan apa-apa melainkan serangga yang menggigit di leherku saja.' Ujar sosok itu dengan arogan kepada Kaelith yang marah. Lalu sosok itu mengangkat tangannya untuk memanggil kembali mantra yang sama seperti sebelumnya, bola api hitam yang mengenai Sora.

Kaelith melihat hal itu, tak gentar akan mantra atau sihir yang ia rapalkan dan terus tetap menembakkan anak panahnya namun dia tidak membidik sosok itu. Melainkan ia membidik ke arah langit dan lonceng katedral itu berdentang sekali lagi. Anak panah yang ditembakkan itu melesat dengan cepat di udara hingga mengenai lonceng berulang kali yang ditembakkan Kaelith secara beruntun.

Bunyi itu layaknya menjadi sebuah paduan suara yang sangat nyaring dan setiap serangan dilepaskan Kaelith seperti menemukan gelombang resonansi tersendiri ketika mengenai lonceng katedral. Pasukan mayat hidup itu membeku ketika mendengar suara lonceng yang berulang-ulang dan kutukan yang masih melekat pada Sora, akhirnya terangkat sepenuhnya. Sora yang sudah tak merasakan dari kesakitan akan efek dari bola api hitam itu, mencoba bangkit lagi.

Dan kali ini, pedangnya kembali ia genggam sempat tergeletak disampingya ketika menahan  serangan itu secara langsung. Sigil yang sama masih membara di dalam dadanya kini menyala di setiap anggota badannya dan setiap langkah, yang sudah cukup melelahkan di tanah yang rusak beserta orang-orangnya di bawah. Bayangan yang mencoba menempel pada Sora itu seperti terdapat api yang terbakar habis layaknya embun beku di dalamnya ada api.

Sora bergerak dengan cepat ke arah sosok itu yang tak membiarkan peluang dihadapannya kini untuk melancarkan serangan balik. Sosok itu meramalkan sihir tombak gelap pada tongkat sihirnya untuk bertarung dengan Sora dari jarak yang cukup dekat ketika melihat Sora bergerak ke arahnya saat ini yang pasukan mayat hidupnya itu membeku karena gangguan pemanggilannya tadi oleh Kaelith sebelumnya. Ketika sosok itu melancarkan serangan yang memiliki jangkupan yang sangat lebar dengan sihir tombak gelap itu, Sora menghindarinya secepat mungkin ke arah samping dan ia menemukan titik celah untuk melakukan serangan. Dengan peluang itu, ia menebaskan pedangnya ke arah sosok itu namun serangan tombaknya beralih untuk menangkis serangan Sora itu dan retakan dari sihir tombak gelap itu tak kuat untuk menahan tebasan Sora yang disertai kekuatan sigil yang membara itu membuat sihir dari tombak gelap itu hancur.

Momen tersebut seperti melihat pertarungan antara penyintas yang mempertahankan kehidupannya dengan melawan sosok penyihir yang telah lama mati dan dibangkitkan menjadi mayat hidup untuk mengambil kehidupan siapapun yang berada dihadapannya. Sihir melawan keheningan yang lahir dari jiwa rusak di dunia yang sudah rusak.

Kaelith bergerak ke arah samping untuk menemukan spot memanah yang bisa melukai sosok itu dan ketika ia sampai di spotnya, ia melepaskan tembakan anak panahnya ke arah sosok itu untuk serangan tambahan bagi Sora yang bertarung itu dan Kaelith juga memerhatikan gerak-gerik dari sosok itu bila melakukan pemanggilan lagi, ia akan mengganggu pemanggilan yang dicoba oleh sosok itu dalam rapalannya disertai dengan dentingan lonceng katedral. Ketika Kaelith sedang melepaskan anak panahnya dan terus membantu Sora dari arah belakang, terlintas ide di benaknya untuk mencoba hal itu. Kaelith berteriak ke arah Sora dengan menahan anak panahnya yang sudah ia bidikkan ke arah sosok itu. 

'MENUNDUKLAH SEKARANG, BODOH DAN COBALAH UNTUK MELEMPARKAN LAGI PEDANGMU ITU KE ARAH LONCENG!' Sora yang mendengarnya langsung menghindar ke arah samping tanpa perlu tahu apa yang dimaksud Kaelith tadi dan Kaelith terus menembakkan sisa anak panahnya yang tersisa itu ke arah sosok itu dengan cepat. Pertaruhan untuk berhasil dalam mengeksekusi ide dari dari rencana itu layaknya gambling bagi mereka saat ini dalam ambang hidup atau mati. Sementara Kaelith sedang menyibukkan sosok itu, Sora langsung melemparkan pedangnya sekali lagi ke arah lonceng. Dan seketika suara itu bergema lagi yang di mana rencana Kaelith sesuai dengan dugaannya, yaitu membuat sosok itu terganggu dan seketika membeku karena Kaelith merasakan bahwa setiap kekuatannya itu berasal dari katedral itu dan lonceng katedrallah yang menyalurkan seluruh energi di dalamnya ke sosok itu hingga terjadilah ketika kekuatan sosok itu melebihi kadar batasnya hingga membuatnya tak bisa mengendalikan kekuatan itu.

Melihat momen seperti itu, Sora langsung mengambil pedangnya yang terjatuh setelah dilemparkannya tadi dengan cepat dan bergerak menyerbu ke arah sosok itu. Sora langsung melepaskan serangannya dan serangannya itu menghancurkan tongkat sihir dari sosok itu untuk tidak bisa melakukan sihir atau pemanggilan yang lainnya dengan menghancurkan bola hitam di ujung tongkatnya. Bola itu hancur berkeping-keping karena hantaman pedang Sora itu mengenainya dengan cukup keras dan terdengar suara pecahan kaca di atas tanah setelah hancurnya bola hitam itu.

Sosok itu terhuyung dan terlihat melemah setelah tongkatnya tak bisa digunakan lagi dan topengnya mengalami retak akibat kekuatan sihirnya seakan-akan meledak karena kelebihan muatan kekuatan yang diberikan tadi. Sora muncul kembali dihadapan sosok itu dengan sigilnya yang saat ini membara di seluruh badannya dan mencengkeram leher sosok itu yang sudah membusuk anggota badannya hingga mendorongnya ke pintu depan katedral itu.

Sebagai penutupan pertarungan mereka berdua itu, Kaelith mendekati Sora yang didepannya terdapat sosok yang sudah tak berdaya lagi karena berhasil dikalahkan dengan kekuatannya sendiri serta ide dari Kaelith sebelumnya. Melihat hal itu, Kaelith menarikkan kembali busurnya dengan anak panahnya dan dilesatkan tepat mengenai jantung sosok itu yang membuatnya mati untuk kedua kalinya tanpa perkataan terakhirnya.

Area sekitar yang tadinya, langit yang penuh dengan kegelapan dan berwarna hitam kepekatan karena sihir dengan jumlah yang sangat besar digunakan sosok itu telah menghilang seutuhnya dan kembali ke keadaan semula yang langit itu kini berwarna merah senja disertai warna keunguan di ujungnya. Lonceng katedral yang tadinya bergema pada saat mereka berdua bertarung, runtuh ke lantainya dan menandakan pertarungan mereka telah usai dan para mayat hidup yang membeku ditempat, satu persatu jatuh ke tanah bahwa sihir pemanggilan sosok itu sudah tak lagi bersama jasad mereka untuk digerakan. Dan untuk terakhir kalinya, yang sudah mati itu kini bisa beristirahat kembali jiwanya.

Keheningan kembali menyelimuti Borreal untuk ke sekian kalinya dari rahasia yang terdalam. Ketika pertarungan telah usai, Kaelith yang sudah mengerahkan seluruh tenaganya dan kekuatannya untuk melawan pasukan mayat hidup yang jumlahnya sangat mustahil untuk bertahan darinya itu berjalan perlahan mendekati Sora dengan berkata, 'Itu… mustahil untuk selamat apalagi memenangkan peluang sekecil ini. Namun, tidak buruk juga hasilnya.' Sora yang mendengar pernyataan Kaelith berada di sampingnya itu, tidak melakukan apapun bahkan menjawab pernyataannya itu. Kaelith hanya bisa mendesah karena rasa capeknya itu kini terasa baik itu fisik dan batinnya. Ia duduk seketika di atas tanah tepat di samping Sora saat dia meletakkan busurnya di belakang punggungnya itu. “Kau memang tak pernah bicara tapi kurasa aku akhirnya mulai memahami beban yang sedang kau pikul hingga saat ini dari melihat caramu bertarung tadi.” Ucap Kaelith setelah memerhatikan ke sekelilingnya itu yang mayat-mayat hidup itu berada di mana-mana hingga melihat Sora yang masih terbakar akan kekuatan sigilnya itu.

Sora menoleh ke arahnya dan hanya bisa melihat raut wajahnya begitu capek dalam menghadapi pertarungan tadi bersamanya.

Lalu—

Gerbang katedral yang sedari tadi tertutup itu terbuka perlahan-lahan dan terdengar seperti ada yang berbisik kepada mereka. ‘Satu dosa mengarah ke dosa lain…’ Lonceng katedral itu sudah tidak berbunyi lagi. Namun, siapa yang membisikkan suara itu kepada mereka saat pintu katedral dihadapan mereka saat ini terbuka itu?

Namun yang pastinya gema pertarungan mereka berdua tadi, masih terasa menggantung di udara katedral sekitarnya yang hancur dan menghitam akan waktu yang terus memakan tembok itu bagaikan usia saja. Sora hanya berdiri sesaat setelah sosok mayat hidup yang menggerakan pasukannya itu tak bangkit lagi dari kematiannya untuk ke sekian kalinya. 

Kemudian—

Tanpa ia sadari, sigil Sora saat ini perlahan memudar dan kembali ke semula yang di mana sebagai manusia tanpa kekuatan sigil lagi. Dan kini, rasa sakit fisiknya itu perlahan terasa dan menjalar ke seluruh area badannya. Lututnya tertekuk di atas tanah dengan perlahan, pandangan Sora mulai kabur, dan tangannya terulur secara naluriah... badannya kini tergeletak di atas tanah dan disertai oleh pendarahan yang hebat dari dadanya yang terluka sebelumnya itu. Kini, nyawa Sora berada di ambang antara kematian dan kehidupan. Kaelith yang masih melihat sekitar dan ketika melihat ke arah Sora kembali, ia tepat pada waktunya untuk melihatnya jatuh tertelungkup keras di atas tanah dengan berlumuran darah darinya. 'Sora?!'

Kaelith bangkit dari duduknya dan bergegas menghampirinya. Sora yang tak sadarkan diri itu kini berada di atas tanah dengan lutut yang lecet, tangannya yang penuh dengan luka dan sayatan pedang yang disertai juga dengan bekas cakaran terdapat di lengannya, dan dadanya itu disertai dengan luka tusukan dari pedang berkarat sebelumnya yang bisa menimbulkan infeksi dalam waktu sekejap bila tak ditangani lukanya dan masih mengalami pendarahan yang sangat hebat. Dengan sevepat mungkin, Kaelith langsung merobekkan sisa kain yang ia punyai itu untuk menghentikan pendarahan di dadanya terlebih dahulu.

Ketika Kaelith sedang menahan pendarahan Sora itu, aroma seperti sesuatu yang terbakar memenuhi lubang hidungnya dan menimbulkan pertanyaan untuk dirinya sendiri saat ini ketika mencium bau tersebut berasal dari Sora. 'Rune... apa yang kau aktifkan hingga seperti ini?' Suaranya pecah, jari-jarinya gemetar saat ia menahan lukanya yang darahnya masih mengalir, dan dia tidak menyadari bahwa saat ini, ia menolongnya tanpa berpikir dua kali. Kaelith memang belum mengenal Sora belum lama ini, namun melihatnya jatuh seperti itu sebelumnya membuat dirinya khawatir akan kehilangan dirinya itu dan terlebih lagi bila tak ada Sora mungkin ia akan mati ketika baru saja sampai di aula kerajaan Borreal yang berada di atas permukaan tadi dan menjadi mangsa bagi Varnished yang menyerbunya.

Dan keheningan di tempat itu sekarang terasa lebih berat daripada kematian yang akan datang. “Sialan! Jangan berani-beraninya kau mati setelah semua ini. Kau belum mengatakan apapun sepanjang waktu. Jangan jadikan hal itu tadi sebagai ucapan selamat tinggalmu, dasar bodoh!” Ujar Kaelith yang merasa frustasi akan melihat Sora yang masih tergeletak dan menahan pendarahannya hingga saat ini. Ia menampar pipinya dengan pelan untuk membangunkannya dari pingsannya itu, Matanya nyaris tidak terbuka sedikitpun hanya terlihat wajahnya begitu pucat pasi saat ini, dan terlebih lagi tidak ada hembusan nafas yang keluar dari hidung atau mulutnya yang disertai dengan bibirnya yang mengering. Hanya bunyi detak jantungnya saja yang berdetak dengan perlahan sebelum berhenti pada waktunya itu. 

Kaelith menggigit bibirnya sendiri untuk menenangkan diri ketika melihat Sora dan kemungkinannya untuk selamat dari ambang kematiannya itu karena luka yang diterimanya begitu fatal dan banyak juga. Kaelith mencoba melihat ke sekeliling area katedral yang hancur itu untuk menemukan sesuatu yang mungkin bisa menolongnya. Namun sayangnya, tidak ada botol ramuan untuk menyembuhkan lukanya, dan tidak ada bantuan seseorang yang bisa membantu Kaelith untuk menyelamatkan Sora yang sedang sekarat itu melainkan tumpukan mayat hidup di sekitarnya yang sudah beristirahat. Hanya jasad dari mayat hidup yang ada di mana-mana, tulang-tulang kering di tanah yang tandus dan gersang, dan keheningan yang sunyi hingga suara angin saja yang bisa didengarkannya.

Lalu—

Dari arah yang jauh sekali namun terdengar suara langkah kaki yang disertai dengan suara dentingan botol-botol dan gerobak yang berjalan di atas permukaan tanah yang tidak datar itu. Ketika Kaelith mendengar hal itu, melepaskan tangannya yang menahan pendarahan Sora tadi dan mengambil busurnya di belakang punggungnya ia taruh dan bersiap menghadapi ancaman lain yang kan datang ke arahnya.

Namun, yang melangkah melalui gerbang katedral besar itu adalah sosok dengan penampilan bertopi bundar dan dimiringkan ke sebelah, mantel yang terbuat dari bulu berwarna putih kehijauan yang dijahit dnegan rapi, dan kereta dorong berderak di belakangnya yang sedari tadi ia tarik untuk dibawa dalam perjalanannya itu penuh dengan aksesoris untuk pengembara, botol-botol ramuan, dan sebagian senjata seperti belati, pisau lempar, hingga anak panah.

Ketika sosok itu melangkahkan kakinya keluar dari gerbang katedral sambil bersiul itu melihat dihadapannya penuh dengan mayat hidup yang tergeletak di atas tanah dan dari kejauhan di samping mayat hidup itu terdapat seseorang yang mengarahkan busurnya ke arah sosok itu yang membuatnya mengangkat kedua tangannya dengan seringai malas. Kaelith melihat sosok itu mengangkat tangan sebagai isyarat menyerah, ia melakukan gestur dengan busur yang ia pegang itu untuk sosok itu mendekat ke arahnya. Mau tak mau, sosok itu dengan desahan malasnya menarik gerobak tariknya dan berjalan menuju ke arah Kaelith hingga mereka berdua bertemu secara langsung dan berhadap-hadapan.

“Baiklah, sekarang… Aku bukan orang yang suka mengganggu momen senja dengan dipenuhi mayat hidup sebagai hiasan untuk kiasan puisi saat ini. Namun, aku melihat sesuatu yang sepertinya meminta pertolongan dengan cara yang tak pernah bisa kubayangkan itu dan juga tidak terlihat seperti keuntungan bagiku untuk melakukannya.”

Kaelith bangkit berdiri dengan busur yang diarahkan ke sosok itu dan anak panahnya itu kembali berderit dengan kencang ketika mendengar sarkasme sosok itu yang menambahkan bensin ke dalam api miliknya itu. “Kau, punya nyali untuk mengatakan hal seperti itu ketika saat terancam. Namun, jangan salah paham untuk hal itu karena aku tidak memercayai seseorangpun di dunia ini dan saat ini aku ingin kau bantu selamatkan dia!” Ujar Kaelith dengan nada mengancam ditambah rasa emosinya akan perkataan sosok itu ke arahnya yang terlihat seperti pedagang yang sedang mengembara namun sosok itu memiliki mulut yang berbisa layaknya ular bila berkata-kata. Mata pedagang itu langsung melirik ke arah Sora dan cukup terkejut hingga bertanya-tanya ke dirinya sendiri mengenai apa yang membuat anak itu seperti ini dengan nada yang dibuat-buat seperti bercanda. “Hmmm. Yang ini terkutuk parah. Pendarahan karena pecahnya sebuah rune yang tak mampu menahan keseluruhan luka yang diterima pemiliknya itu. Sepertinya ini semacam sebuah sihir kuno? Atau sihir yang sangat berbahaya?” Kaelith menyerbunya karena tak bisa menahan perilaku pedagang itu yang bertele-tele. “Aku tidak peduli apapun itu, lakukanlah sesuatu atau anak panah ini yang menjawab pertanyaanmu tadi!” 

Pedagang pengembara itu mendecakkan lidahnya dan merasa apa yang dilakukan Kaelith itu membuat dirinya ikut kesal namun ia membalasnya dengan sarkasme khasnya dan disertai godaan juga. “Panik tidak membuatmu lebih cantik, Sayang. Tapi aku punya salep yang mungkin bisa mengobati luka fisiknya itu, ramuan yang diseduh dari lembah yang terkutuk untuk menangkal racunnya di dalam tubuhnya beserta infeksi lukanya itu, perlengkapan untuk menjahit sayatan, robekan, hingga bocor yang terbuat dari tulang orang suci yang gugur, dan ah, ya—” Pedagang itu mengeluarkan botol kecil yang bersinar berwarna ungu kebiruan. “Sebuah ramuan pengikat jiwa. Sakit rasanya saat dimasukkan tapi itu akan menstabilkan tandanya… bila nasibmu beruntung jika bisa selamat dari apa yang disebut menari-nari di atas tali yang sebagai pertaruhan antara kehidupan dan kematian.” 

Kaelith tidak menunggu pernyataannya selesai dan langsung saja ia mengambil botol ramuan itu dari tangan pedagang pengembara. Kaelith dnegan cepat menghampiri Sora dan memastikan detak jantungnya terlebih dahulu sebelum memasukkan ramuan itu ke dalam mulutnya. Ketika suara detak jantungnya terdengar pelan dan masih ada, ia berlutut di sampingnya dan memiringkan kepala Sora dengan lembut. Matanya itu melihat wajah Sora yang penuh dengan bercak darah hitam dan debu yang mengepul di wajahnya yang kotor itu.

“Dasar bodoh, kau tidak tahu seberapa pentingnya nyawa untuk dijaga dalam setiap kehidupan semua makhluk.” Gumam Kaelith dengan pelan ketika membuka botol ramuan pengikat jiwa dari pedagang itu dan menuangkannya ke dalam mulut Sora. Setelah dituangkan ramuan itu ke dalam mulut Sora, tiba-tiba tubuhnya gemetar perlahan seperti mengerang rasa kesakitan yang dialaminya dengan luka seperti itu. Pembuluh darah di sekitar dadanya berhenti mengeluarkan pendarahan lagi dan semua luka yang didapatnya itu dengan cepat mengering bahkan lubang tusukan pedang di dadanya itu.

Sora mencoba untuk berteriak dengan mulutnya yang terbuka lebar itu dalam keadaan mata yang masih tertutup itu namun mengngat ia bisu dan tidak mungkin sbeuah suara keluar dari mulutnya itu. Mulutnya terbuka dan diikuti oleh rahang yang terkatup begitu erat hingga membuat mengertakkan giginya. Dan tak lama setelah itu, Sora kembali tenang setelah penyembuhan lukanya berhasil dari ramuan pengikat jiwa itu namun belum juga kunjung bangun dari pingsannya. Detak jantungnya itu kini kembali berdenyut dengan normal.

Kaelith yang tak menduga dari efek ramuan itu seketika bisa mengistirahatkan kembali badannya dengan memindahkan kepala Sora dari pangkuannya itu dan memindahkan kepalanya itu di atas tanah tepat di sampingnya dengan matanya yang sudah lelah itu bisa tenang kembali pada akhirnya.

“Lain kali, lebih baik kau memberitahuku sebelum kau mencoba membunuh dirimu sendiri.” Timpal Kaelith setelah melihat kondisi Sora yang terlihat membaik untuk saat ini. 

Pedagang itu bersiul ketika pertama kalinya melihat efek obat itu berkerja langsung tanpa menunggu waktu beberapa hari saja dan hal itu sebuah momen langka yang perlu dilihat dari kejadian itu secara langsung. Pedagang itu mencoba membuka pembicaraannya dengan Kaelith terkait ramuan yang ia ambil darinya sebelumnya. “Sangat menyentuh dan sangat puitis untuk diabadikan. Sekarang, untuk harganya—” Belum sempat menyelesaikan perkataannya, Kaelith langsung berdiri dan me ngetahui apa yang dimaksud oleg pedagang pengembara itu. Busurnya yang berada di sampingnya itu langsung digenggam dan mengambil anak panhanya lalu membidiknya tepat dihadapnnya saat ini dengan pakaiannya yang masih berlumuran darah dari mayat-mayat hidup tadi.
Matanya menatap pedagang itu dengan tatapan sedingin es lalu berkata, “Ucapkan kata ‘harga’ sekali lagi dan aku akan menembakkan anak panahku ini menembus tulang belakangmu melalui gigimu.” Tidak kaget akan reaksinya seperti itu, pedagang itu hanya bisa tersenyum lebar dan menjawabnya dengan godaan sekali lagi,  “Ahhh... Aku suka tipikal wanita sepertimu itu. Selera yang sangat liar.” Dirasa tugas dari pedagang itu selesai dan ia tak mendapatkan keuntungan apapun selain dirampok, ia hanya bisa mendorong gerobaknya sambil mendesah akan tidak adanya pemasukan melainkan pengeluaran dan kerugian yang ia dapatkan hari ini. 

“Baiklah, para pencinta kehancuran. Nikmatilah istirahat kalian saat ini, Namun, Badai berikutnya sudah menanti kalian di sana nantinya. Sampai jumpa di lain waktu mungkin.” Setelah mengucapkan salam perpisahan, pedagang itu memutuskan untuk pergi ke arah sisi lain katedral dan bersiul dengan nada yang acak setiap kali ia berjalan.

Kaelith yang memerhatikan pedagang itu hingga tak terdengar lagi suara siulannya itu, duduk di samping Sora yang masih terbaring dengan pedang yang tergeletak di sampingnya itu. ia menyeka keringat dahinya dan wajahnya kembali tenang namun masih mengkhawatirkan Sora yang masih pingsan itu dan untuk waktu yang lama, mereka tidak bergerak dari tempat mereka yang berada di luar katedral.

Kaelith tidak bisa tidur karena masih memikirkan apa yang terjadi sebelumnya saat ia bertarung dengan Sora. Ia terus terbayang-bayang akan tindakan Sora yang dilakukannya itu untuk melindungi diirnya bahkan Kaelith sendiri hingga saat ini tidak terluka oleh sayatan pedang atau goresan luka sedikitpun selama ia bertarung dengan Sora. Hingga ia memutuskan untuk mengumpulkan kayu bakar dan membuat api unggun untuk selalu mengawasinya saat jam-jam menjadi pecahan takdir yang menunggu untuk melihatnya membukakan matanya kembali.

Dan kemudian—

Jari-jari Sora mulai berkedut saat angin malam berhembus melaluinya, alisnya berkerut karena mimpinya saat ini mungkin, dan suara nafas yang keluar dari mulutnya itu keluar dengan tajam seperti udara yang diambil dari dasar yang tak berujung dan begitu tergesa-gesa. Dia belum terbangun dari pingsannya itu namun, di dalam dirinya terdapat sesuatu yang menantinya bahkan dalam tidurnya sekalipun.";

                $paragraf = preg_split('/(\r\n|\n|\r){2,}/', $naskahLengkap);
                $naskahTerformat = '';
                foreach ($paragraf as $p) {
                    if (!empty(trim($p))) {
                        $naskahTerformat .= "<p>" . trim(nl2br($p)) . "</p>";
                    }
                }
            @endphp

            <div style="font-size: 1.1rem; line-height: 1.8;">
                {!! $naskahTerformat !!}
            </div>

            <hr class="my-5">

            <div class="d-flex justify-content-center flex-warp gap-3">
                <a href="/story/the-unkindled/bab-tiga" class="btn btn-lg btn-contrast">Kembali ke Bab Sebelumnya</a>
                <a href="/story/the-unkindled/bab-lima" class="btn btn-lg btn-contrast">Lanjut ke bab berikutnya</a>
                <a href="/story/the-unkindled" class="btn btn-lg btn-contrast">Kembali ke Halaman Novel</a>
            </div>

        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    document.cookie = "lastRead_the-unkindled=bab-empat; path=/; max-age=31536000; SameSite=Lax";
</script>
@endpush