@extends('layouts.app')

@section('title', 'Bab Lima - The Unkindled')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            
            <h2 class="text-center mb-4">Bab Lima: Di Balik Selubung Api</h2>
            <hr class="my-4">

            @php
                $naskahLengkap = "Dunia ini seperti kayu yang terbakar oleh api hingga menjadi arang dan abu namun tidak bagi Sora yang masih pingsan. Dunia di sekelilingnya itu penuh dengan penderitaan dari setiap pengalaman ia miliki dan masa lalunya. Sora yang masih pingsan, menemukan dirinya itu berdiri di tengah-tengah padang gersang dan berwarna merah yang sangat luas dan tak memiliki ujung ketika matanya memandang jauh ke arah padang itu. Langit di atasnya berwarna merah seperti telah terbakar oleh sesuatu dengan kumpulan asap hitam di atasnya dan di bawah kakinya bukan tanah yang ia pijak melainkan kumpulan abu-abu yang terbentuk dari pembakaran.

Sora yang tampak bingung karena sebelumnya ia mendapati masih bersama Kaelith sebelumnya itu kini berada di sebuah tempat asing tanpa ada kehadiran Kaelith di tempat itu hingga ia menyadari setelah ia melihat ke dirinya sendiri dan menemukan suatu hal yang tak mungkin terjadi, ia kembali menjadi seorang anak laki-laki dan kini ia mengetahui bahwa kini ia berada di alam bawah sadarnya. Sora yang melihat dirinya yang telanjang tak mengenakan baju apapun dan terlihat dirinya seperti arwah yang bergentayangan saat ini, badannya terasa dingin ketika angin berhembus ke arahnya, dan terlebih lagi dia seorang diri di sana di tengah-tengah padang gersang itu dengan sendirian.

Ketika Sora menyadari hal itu, ia mencoba untuk mencoba berteriak apakah ia bisa berbicara atau tidak? Namun, tidak ada suara yang keluar dari tenggorokannya itu dan masih sama seperti biasanya. Ketika ia melihat di depannya itu, ia melihat bayangan gubuk yang mirip seperti gubuk yang pernah ia tinggali di waktu masa kecilnya dengan ciri khas daari bagian depan pintu gubuk tua dan lusuh itu, kain yang robek sebagai penandanya dan di sampingnya, terlihat satu sosok yang duduk di dekat pintu gubuk tua itu dengan kursi goyangnya. Tidak seperti seorang manusia pada umumnya ketika Sora perlahan mendekatinya dengan perlahan, dia seperti sosok yang hampir menyerupai bayangan yang terdapat sesuatu aura yang sangat berbahaya ketika Sora merasakannya. Ketika Sora semakin dekat dan terlihat jelas bahwa sosok itu adalah... seorang wanita tua renta yang membungkukkan badannya sambil duduk di kursi goyangnya itu. Sora tak mengetahui siapakah dia namun Sora memiliki perasaan tidak enak ketika melihat hal ini.

Wanita tua itu menoleh ke arah Sora dengan cepat, wajahnya saat ini memberikan ekspresi yang penasaran akan Sora itu dan senyum lembut di wajahnya menunjukkan maksud tersendiri yang wanita tua itu ingat... Sesuatu yang seperti sebuah ramalan dari masa lalu dan membandingkannya dengan saat ini ketika wanita tua itu melihat Sora. Lalu wanita tua itu berkata sambil menunjukkan jarinya yang keriput ke arah Sora, 'Kau seharusnya tidak selamat dan seharusnya tidak berada di dunia saat ini.'

Sora yang mendengar perkataan wanita tua itu kaget dan dengan perlahan berjalan mundur tak lama dari itu sosok lain muncul berada di belakangnya ketika Sora berbalik arah ke belakang dan terdapat sosok itu sangat ia kenal dan ingin menemuinya walau jaraknya tidak jauh darinya. Itu Eyla Varn, wanita yang membesarkannya ketika orang lain tak mau membesarkannya dan Sora sendiri dianggap sebagai anak terkutuk yang tak diinginkan oleh seorangpun kecuali Eyla yang mau membesarkannya hingga ia berumur 7 tahun.

Mata Sora tidak bisa mempercayai bahwa ia akan melihat Eyla lagi namun suasana dan kondisinya saat ini tidak menunjukkan sesuatu yang membuatnya terharu dan rasa ingin memeluk seorang ibu yang ia anggap itu melainkan ketakutan ketika melihatnya sangat berbeda dari yang ia kenal. Sora yang hanya bisa terdiam melihat Eyla itu, Eyla pada akhirnya mendekati Sora dengan perlahan dan ketika sudah dekat, ia hendak ingin meraih Sora dengan menjulurkan tangannya namun tangannya yang hendak ingin menyentuh Sora berubah menjadi abu yang berterbangan oleh angin yang berhembus sebelum menyentuh wajah Sora dan wujud Eyla tidak ada sama sekali ketika abunya dibawa angin entah kemana. Sora yang melihat ini hanya bisa mematung dan merasa sesuatu yang tidak beres hingga membuat dadanya terasa sakit sekali saat ini. 

Ketika Eyla menghilang bagaikan bak abu yang diterbangkan angin itu, dari arah kejauhhan di belakang abu Eyla terdapat sesuatu yang menjulang tinggi yang sepertinya seseorang yang membawa lentera di genggaman tangannya, berselimut tulang layaknya malaikat maut, wajahnya tertutupi oleh tudung hingga tidak terlihat dari kejauhan, tangannya yang menggenggam sebuah lentera itu bagaikan ia sedang menarik sebuah rantai yang terbuat dari gema untuk setiap orang yang menjeritkan sesuatu yang tidak pernah orang lain ucapkan untuk meminta sebuah petunjuk untuk menerangi jalan mereka yang gelap itu. Makhluk itu berjalan ke arah Sora yang sedang mematung ketika melihatnya itu dan mendekatinya seraya berbisik kepadanya, “Kau lahir dari pengabaian, kau dibentuk oleh kesunyian, dan kau dipilih... untuk tetap dilupakan oleh sebagian besar orang. Namun, apa yang membuatmu terus berjalan wahai anak muda?” 

Lentera yang digenggam sosok itu berubah menjadi rantai yang panjang dan membara seperti bara api dan melilit tangan Sora ketika rantai itu dihempaskan ke arahnya. Sora mencoba melepaskan dirinya dari rantai itu tetapi hanya bisa pasrah dengan keadaanya itu. Hanya rasa panas yang meningkat di bagian tangannya yang perlahan menjalar ke area tubuhnya perlahan-lahan ke arah bahu hingga badannya ikut membara seperti bara api yang berkedip-kedip di sekitar area tubuh Sora saat ini. Dengan lilitan rantai yang panas itu membuat rune di dalam dadanya terbakar karena efeknya yang sangat panas dan memicu untuk aktif kembali namun runenya yang menyala saat ini bukan sebagai luka yang didapat darinya melainkan sebagai sigil perlawanan terhadap rasa panas dari rantai yang melilitnya.

Ketika runenya itu berkobar-kobar untuk melawan apa yang tengah melilit di tangannya itu membuat rantai itu yang membara seperti bara api hancur berkeping-keping dan sosok itu mendesis ketika melihat kekuatan rune Sora itu namun tak lama desisan sosok itu terdengar sebuah badai merah muncul berada di dekatnya itu yang perlahan semakin membesar. Sora menahan setiap hembusan yang sangat keras dan memaksanya untuk masuk ke dalam badai itu dalam tarikannya dan sosok itu terbawa oleh badai merah itu begitu saja hingga lenyap dari hadapan Sora begitu saja.

Kemudian—

Sora yang sedari tadi menahan dengan kedua tangannya dari sebuah badai merah tiba-tiba saja mendapati dirinya di tempat yang penuh dengan kegelapan seolah-olah ia saat ini berpindah ke tempat yang lainnya secara tiba-tiba. Kini, tak terlihat apapun baik tanah yang gersang, gubuk tua yang ia kenali, sosok yang membawa lentera namun berubah menjadi rantai yang melilit tangan Sora, wanita tua yang duduk di kursi goyang, serta Eyla yang berubah menjadi abu itu tak adalgi keberadaannya selain keheningan dan kegelapan apa yang ia lihat dan dengar. Tiba-tiba dari arah belakang Sora, sebuah tangan yang diletakkan di bahu Sora. Seketika Sora berbalik badan dan menemui Kaelith yang berada di belakangnya itu. Busurnya diletakkan di belakang punggungnya itu dan di tangannya itu ia sedang memegang sebuah obor yang menyala di tengah kegelapan itu. “Kau tidak bisa tinggal di sini, tidak selama dunia ini masih menghembuskan namamu untuk terus menjadi saksi atas kehancurannya itu.” suara Kaelith yang bergema dan menyerahkan obor itu padanya sebagai penerang jalan baginya yang berada di depan tanpa adanya cahaya yang menuntunnya.

Api dari obor itu melonjak ke arah dada Sora sektika, api itu tidak membakar dirinya melainkan mengikatnya agar lilin di dalam hatinya itu tidak akan padam sebagai pengingat akan perannya itu dan sebagai sebuah bentuk dari seorang manusia yang masih hidup di atas penderitaan yang pernah ia lalui. Tepat sebelum mimpi buruk itu terkoyak menjadi sebuah kegelapan yang menjadi lebih gelap dibandingkan sebelumnya itu, Sora tak melihat Kaelith lagi yang berada di hadapannya itu yang termakan oleh kegelapan di dalamnya dan menghilangkan sosoknya itu. Namun, sebuah bisikan entah darimana asalnya itu terdengar di telinganya saat ini dan yang pastinya bisikan itu bukan darinya. Bisikannya yang awalnya terdengar samar-samar kini semakin terdengar mendekati ke arahnya hingga sebuah suara muncul dengan nada yang serak dan pecah oleh keheningannya itu yang mengatakan, 'Aku belum usai.'


Kembali di depan katedral, 

Tubuh Sora tersentak dengan tiba-tiba yang membuatnya terbangun dengan bekas luka dan darah yang dibalutkan oleh kain yang robek itu melihat kondisi sekitarnya tanpa memedulikan rasa sakitnya yang hebat di sekitar tubuhnya itu. Kaelith yang sedari tadi mengasah anak panahnya dengan batu asah miliknya itu terkejut ketika melihat Sora yang sudah terbangun dari pingsannya itu dan dengan tanpa disadari, ia menjatuhkan batu asahnya lalu bergegas ke sisi Sora yang baru saja siuman itu. Mata Sora terbuka dengan lebar itu mencoba mengetahui kondisi saat ini dan terlihat sinar samar yang hanya sesaat dari matanya itu dengan tanda runenya masih membekas di dadanya yang terlihat seperti bekas sebuah luka yang mencekung sedikit ke arah dalam dadanya. Bibirnya yang kering itu terbuka dan Sora mencoba ingin memastikan satu hal saja untuk hal ini namun tetap saja tidak ada suara yang keluar sekalipun dari dalam mulutnya itu. Kaelith yang melihatnya seperti itu mencoba menenangkan dirinya dan berbicara kepadanya dengan nada pelan yang mengkhawatirkan itu. “Hei… tenanglah, kau masih belum mati.” Seluruh tubuh Sora itu kini dipenuhi oleh keringat yang bercampur dengan darah yang sudah kering di kulitnya itu di sebagian anggota badannya setelah mendapati dirinya mimpi buruk yang dialaminya saat ia pingsan sebelumnya.

Kaelith menuangkan beberapa tetes air dari botolnya untuk membantu Sora meminumnya dan Sora membenagunkan badannya ke arah Kaelith yang membantunya itu dengan keadaan masih lemah dan banyak luka yang tertutupi oleh kain sobek tetapi saat ini dia sudah sadar dan mencoba untuk memaksakan tubuhnya untuk bangkit dari luka yang diterimanya. “Kau membuatku sangat takut hingga melihatmu berjudi dengan kematianmu sendiri seperti orang bodoh saja.” Gumam Kaelith kepada Sora setelah ia memberikan botolnya ke Sora agar meminumnya dengan sendiri. Sora yang menyisakan air itu di dalam botolnya, mengulurkan tangannya dengan botol yang ia genggam dan penuh luka yang masih basah namun pendarahannya berhenti untuk memberikan botolnya.

Kaelith mengambilnya dan untuk sesaat, tatapannya ke arah Sora bukan sebagai seorang pejuang, melainkan seseorang yang hanya peduli kepada orang yang menyelamatkan nyawanya sebelumnya. Hanya dua orang yang masih bertahan dari kerusakan dunia yang ingin merusak mereka secara perlahan-lahan itu, duduk di antara debu dan abu disekitar mereka, reruntuhan dewa-dewa yang terlupakan di bawah kaca patri yang pecah sejak lama, dan api unggun yang dibuat Kaelith untuk menjaga cahaya mereka tetap ada di tengah gelapnya dunia itu bagi mereka.

Kaelith memecah kesunyian dengan senyum tipis sambil mengingat-ingat kejadian tadi yang hampir membuat nyawanya melayang bila tidak bersama Sora sebanyak 3 atau 5 kali lebih mungkin. “Lain kali, biarkan aku hampir mati.” Ujar Kaelith dengan menatap kembali ke arah api unggun yang menyala di tengah-tengah mereka itu. 

Setelah mereka beristirahat cukup lama hingga warna langit di atas mereka perlahan berubah kehitaman dan Sora yang dipaksakan untuk bangkit dari sakit lukanya di sekujur badannya itu, berdiri diam dan sedang memeriksa pedangnya lalu diletakkan di sarung pedangnya yang berada di samping pinggulnya. Tidak ada nama yang terukir di gagangnya dan tidak ada keahlian yang perlu dibicarakan darinya selama memegang pedang itu yang menajdi saksi atasnya namun, pedang itu terasa berbicara dengan tangannya seperti mengatakan bahwa ia seharusnya pemilik dari pedangnya itu.

Kaelith yang berada tak jauh dihadapan Sora, tengah mengkemasi seluruh anak panah yang ia kumpulkan di tabung anak panah belakang punggungnya itu. Busur yang diterimanya di ruangan sebelumnya, bergantung di belakang punggungnya bersama dengan tabung anak panahnya disampirkan di punggungnya bersampingan. 'Jadi, kau masih belum mati hari ini dan sebaiknya kita tetap berjalan serta melihat apa lagi yang ada di dalam gerbang katedral ini.' Ujarnya kepada Sora sembari berdiri dan diikuti oleh Sora yang mencoba berdiri dengan susah payah dan akhirnya ia mampu memaksakan untuk tetap berjalan meskipun tak seutuhnya sembuh dan setidaknya ia bisa bertarung bila diperlukan.

Mereka berjalan menuju depan gerbang katedral itu yang sedikit terbuka itu dan mereka memasuki celahnya yang cukup untuk satu orang saja. Ketika mereka memasuki katedral itu, mereka menemukan di dalamnya penuh dengan bangku-bangku yang rusak terbuat dari kayu itu berserakan di mana-mana sedangkan mimbar yang berad di jauh sana masih berdiri walau terlihat terdapat bekas terbakarnya kayu yang sudah lama itu. kaca-kaca diatasnya itu berwarna-warni yang sudah pecah sebagiannya dansebuah lambang yang terpapang di atas mimbar usang itu hancur sebagiannya dengan simbol aneh yang menggambarkan tengkorak dari kepala serigala yang sebagiannya hancur itu.

Ketika mereka berdua keliling di sekitar area katedral itu, mereka menemukan sebuah tangga ke arah bawah tanah yang berada di belakang mimbar itu yang tertutupi oleh mejanya yang sedikit bergeser itu hingga terlihat sebuah celah yang membuat mereka berdua penasaran hingga Kaelith mendorong meja tersebut hingg terlihatlah sebuah tangga yang mengarah ke bawah tanah itu. mereka berdua menuruni setiap anak tangga itu yang menuju ke arah suatu tempat di bawah tanah itu dengan menemukan obor di samping dindingnya yang tak menyala itu. Kaelith mengambil salah satunya dan menyalakan obor itu dengan batu apinya yang dipercikan secara berulang-ulang hingga api muncul di obor itu yang menerangi jalan mereka di depan.
Mereka berdua terus berjalan ke arah yang ditujukan oleh tangga itu dan hanya suara selain gema langkah kaki mereka. Ketika anak tangga itu menemui ujungnya, terlihat di depan mereka saat ini sebuah gerbang yang sangat besar seperti gerbang itu menutup rapat sesuatu yang menjadi sebuah rahasia di bawah tanah katedral itu dan sesosok tubuh yang merosot di antara pilar rusak terlihat di depan mereka berdua dan tentu saja, hal ini membuat Sora secara naluriah melangkah maju dengan perlahan untuk mendekatinya dan tangannya menggenggam pedang. 

Ketika Sora ingin memastikan sesuatu dari sosok itu, sosok itu bergerak dan masih bernafas saat ia dengan sigap mendengar langkah kaki yang mendekat ke arahnya itu dan mempersiapkan pedangnya yang berada di sarungnya itu tanpa harus dikeluarkannya. Sosok itu adalah seorang pria dengan zirah usang yang memiliki simbol di zirahnya dengan gambar seekor serigala yang sama persis gambarannya dengan simbol di atas mimbar kateddral itu. Wajahnya sebagian tertutup topeng baja yang setengahnya itu masih memperlihatkan area wajahnya dan usang. Sosok itu menatap mereka dengan cukup lama dan mengetahui bahwa mereka adalah manusia dan bukanlah monster juga bukan musuh mereka saat ini. Namun, tidak cukup ramah juga bagi mereka berdua yang melihat sosok itu sebagai ksatria yang sudah termakan oleh peradaban waktu yang terlihat dari zirahnya hingga topengnya yang sudah usang itu. 'Pembawa keheningan lainnya dan seorang pemanah bayangan dengan mata yang telah melihat terlalu banyak.' katanya dengan suara lirih dan lelah. Kaelith menyiapkan busurnya sebagai tanda kewaspaannya sedangkan Sora yang mendengar perkataan ksatria itu menurunkan kewaspadaannya ketika ia tahu maksud dari sosok itu. 

“Dan kau?” Tanya Kaelith dengan mengarahkan bidikan busurnya ke arah ksatria itu dan ksatria itu bereaksi dengan mengankat kedua tanganya sebagai tanda bukan permusuhan bagi Kaelith yang sudah membidiknya, “Namaku Vael. Dulu seorang kesatria kerajaan Borreal dan sekarang hanya peninggalan dari masa lampau. Seperti yang kalian lihat, semua yang ada di sini sudah lenyap oleh peradaban waktu yang cukup lama.” Mendengar hal itu dari Vael sang ksatria tua dari kerajaan Borreal itu, Sora melangkah ke arah Vael dengan perlahan. Vael yang kebingungan dengan memiringkan kepalanya ketika melihat Sora mendekatinya itu, mencoba untuk membaca gerak-gerik Sora itu dan apa yang ia ingin lakukan terhadapnya namun ia membiarkan Sora yang berada di hadapannya itu yang hanya memerhatikannya.

“Aku melihat kalian berdua telah mengalahkan penyihir itu di atas. Aku mendengar sebuah lagu yang dinyanyikan saat darahmu dan dentingan pedangmu itu jatuh di atas batu.” Ujar Vael dengan perlahan dan mencoba untuk tidak mengeluarkan senjatanya sebagai ancaman bagi mereka berdua. “Jika kau datang ke sini untuk keselamatan, kau tidak akan menemukannya. Namun, Jika kau datang untuk mencari jawaban... mungkin kau akan menemukan apa yang kalian cari di balik pintu ini.” Tambah Vael dan pernyataan Vael, membuat Kaelith menyipitkan matanya dengan penuh kecurigaan apa yang dimaksud Vael itu. “Dan bagaimana jika kita datang untuk mengakhiri apa yang telah menyerang kita dari kerajaan ini?” Tanya Kaelith dengan penuh sinis itu kepada Vael untuk menemukan jawaban dari pernyataan sebelumnya sebagai atas tindakannya yang terlalu abu-abu baginya. Vael hanya bisa tertawa pelan ketika mendengar pertanyaan Kaelith itu dan pertanyaan itu seolah-olah bergema terlalu lama di dinding belakangnya yang sedang mengejek pernyataan sebelumnya itu. “Kalau itu tujuan kalian, maka kalian berdua dikutuk atau dipilih.” Jawab Vael dengan tenang yang membuat jawabannya terlihat seperti tak memihak siapapun kecuali menguntungkan bagi diirnya ketika mendengar hal itu.

Keheningan yang terjadi setelahnya terasa berat bukan karena bahaya, tetapi sejarahnya setelah mereka mengetahui dengan apa yang Sora dan Kaelith alami di depan kaetdral tadi serta melihat ksatria yang masih hidup dan mengabdi kepada kerajaan yang telah lama hancur itu. Sora yang semakin penasaran dengan Vael, mendekatinya lagi dan kini hanya rasa penasaran tentang dirinya sebagai ksatria yang sudah cukup lama mungkin mengabdi kepada kerajaan Borreal ini. Vael melihat ke arah matanya yang menunjukkan sesuatu dan ia mengetahui bahwa Sora adalah orang yang tak bisa ia bayangkan itu. “Kau tak bisa bicara, bukan? Namun, kesunyianmu seakan-akan menjeritkan sesuatu yang banyak orang tak ingin dengar.” Ujar Vael ketika mengetahui juga bahwa Sora sama sekali tak berbicara dan ia bisa mendengar sesuatu apa yang ingin ia ucapkan dalam lubuk hatinya melalui apa yang dia alami saat pertarungan di atas tadi melawan penyihir itu dari luka-lukanya yang masih terasa segar untuk dilihat.

Vael mencoba sesuatu kepada Sora, mungkin saja ia bisa melakukan sesuatu dengan benda yang telah lama ia simpan dan menurut Vael yang tak tahu cara kerja benda itu mencoba Sora mungkin bisa melakukan sesuatu dengan benda itu. Vael meraih ke kantong celana zirahnya itu dan memperlihatkan pecahan sebuah sigil yang terlihat seperti pecahan kaca yang tengah berkilau berwarna merah serta berdenyut layaknya jantung namun samar untuk dilihat. “Ini... adalah sisa dari sigil kerajaan. Darah yang sama yang telah mengutuk kerajaan ini yang juga mengalir melaluinya. Sentuhlah dan aku ingin kau melihat apa yang mereka kubur itu dan cobalah jelaskan kepadaku apa yang kamu lihat di dalam sigil ini.”

Tangan Kaelith bergerak ke lengan Sora dengan cepat yang mengetahui hal itu sama halnya dengan rune yang Sora aktifkan tadi mungkin memiliki efek yang sama. “Hati-hati.” Ujar Kaelith dengan pelan yang khawatir terhadapnya saat ini penuh luka itu. Sora mengangguk kepada Kaelith bahwa ia paham dan tidak ragu untuk menyetuh sigil yang ditawarkan Vael tadi. Ia mengulurkan tangan dan memegang sigil itu yang terasa dingin pecahan itu saat ia genggam.

Rentetan hasil dari Penglihatannya:

Dunia yang Sora lihat itu seperti berdarah namun putih warnanya seakan-akan darah yang berwarna putih itu adalah darah dari kerajaan utara yang tertupi oleh salju, yaitu kerajaan Borreal. Sora berdiri di tengah-tengah Borreal yang berlatar berabad-abad sebelumnya yang kehidupannya penuh dengan kejayaan dan dengan era keemasannya.

Seruan festival setiap orang yang tertawa dari seluruh penjuru kerajaan Borreal, dentangan lonceng-lonceng yang berbunyi terdengar diseluruh area kota, dan menara yang menjulang tinggi hingga terlihat seperti mencapai awan di atasnya itu yang di mana menara itu adalah kastil dari kerajaan Borreal itu sendiri, yaitu tempat dimana para raja pernah berbicara kepada para dewa dan duduk di atas singgasananya sebagai pemimpin dari kerajaannya.

Kemudian—

Sebuah api dan jeritan orang-orang datang  dari segala area kerajaan Borreal. Sosok berjubah yang tidak diketahui asalnya itu melantunkan mantra di depan takhta kerajaan Borreal itu yang meramalkan sebuah mantra disertai dengan ritual didalamnya itu dan sebuah ritual yang menyebabkan akhir dari keemasan dan kejayaan dari kerajaan itu.

Langit retak dan dari lubang di atasnya, gerombolan Varnished yang datang dari arah atas layaknya menghujani seluruh kerajaan seperti malaikat-malaikat kematian yang turun ke bumi dan mengakhiri seluruh kehidupan di area sana telah dimulainya sebuah era kekacauan dan akhir itu terjadi.

Orang-orang berubah menjadi mayat hidup akibat ramalan seorang sarjana muda yang menjadi penasehat kerajaan itu membuatnya layaknya boneka yang bisa ia gerakkan dan juga menjadi apa yang seperti di bawah tanah kuburan terdalam.

Raja yang duduk di singgasananya melihat kekacauan yang terjadi di seluruh kerajaannya itu terbakar bersama singgasananya dari dalam istananya dan raut wajahnya hanya bisa senyum pahit ketika ia dibodohi oleh penasehat yang selama ini ia percayai saat ajalnya hingga terjemputnya kematian sang raja di takhtanya yang terbakar oleh api.

Hal terakhir yang dilihat Sora setelah semua kerajaan sudah tak bersisa melainkan genangan darah, abu, hingga kekacauan yang terjadi di sekitarnya dari apa yang ia lihat itu menemukan seorang anak yang hanya berdiam diri di tengah kekacauan terjadi. Anak itu berdiri di antara reruntuhan bangunan dan wajahnya yang begitu sangat familiar baginya. Tak lama dari Sora memerhatikan anak itu, kegelapan menjalar ke seluruh area itu tanpa terkecuali seperti sebuah tirai yang menutupi pandangan Sora datang menyelimuti memori pecahan batu itu.

Kembali ke masa kini:

Sora tersentak ke belakang ketika sudah sadar saat ini setelah melihat apa yang harusnya tak boleh dilihat oleh siapapun mengenai hal ini dan Vael yang melihat Sora seperti itu, langsung menayakannya. “Kau melihatnya, bukan? Kehancuran itu? Bisakah kau menceritakan atau jelaskan dari apa yang kau lihat tadi?” Sora yang masih tak bisa mempercayai apa yang baru saja ia lihat dan tak ingin menjelaskan kepada Vael hingga Kaelith yang melihat reaksi Sora seperti itu, terkejut dan menanyakan perihal ini ke Vael. “Apa-apaan itu?” Vael menoleh ke arah Kaelith dan mencoba menjelaskan apa yang ia ketahui mengenai sigil yang ia berikan ke Sora itu. “Sebuah kenangan, yang tersimpan di dalam pecahan batu ini dan tersembunyikan oleh waktu akan kebenarannya.” Vael menatap mereka berdua dan melihat Sora yang mengelengkan kepalanya itu kepadanya, Vael mengerti apa yang ia maksud sehingga Sora tak ingin menjelaskannya kepada Vael mengenai apa yang ia lihat tadi dan Vael melanjutkan kembali perkataannya. “Kau ingin mencapai kebenaran di balik ini, bukan? Jika hal itu yang kalian inginkan, kalian akan membutuhkanku untuk mencapainya. Di depan sana, ada jalan yang terbagi menjadi tiga cabang yang salah satunya mengarah ke kematian, satu lagi mengarah ke kegilaan, dan yang terakhir mengarah ke sebuah kebenaran yang kalian ingin ketahui tentunya.” 

Mendengar hal itu dari Vael, Kaelith langsung membawa Sora ke belakang untuk berbicara empat mata dengannya mengenai perkataan Vael dari awal hingga akhir yang membuatnya sangat mencurigai pergerakannya yang tak pasti itu. Sora memahami maksud Kaelith bahkan ia hendak ingin berbicarapun, Sora mengangkat tangannya dan mengangguk pelan bahwa ia tahu akan hal tersebut. Kaelith hanya bisa menatap Sora dalam keadaan pasrah dan kembali lagi ke hadapan Vael dan Sora menganggukkan kepalanya sebagai persetujuan apa yang ditawarkan Vael tadi “Kalau begitu, ikuti aku. Tapi jangan tanya jalan mana yang kita ambil selagi kau siap untuk kehilangan apa yang kau tak kira dari dirimu itu.” kata Vael, sambil berbalik ke arah pintu di depannya itu yang kini telah terselimuti kabut yang berwarna ungu dari celah abwah pintu itu.

Pintu itu terbuka dengan lebar dan berderit saat mereka menemukan sebuah anak tangga yang menuju ke arah bawah lagi untuk menuruninya dan lebih dalam dari yang sebelumnya seperti di katedral. Arah ini menunjukkan arah untuk masuk ke jantung Borreal yang telah lama terkubur oleh sebuah kebenaran yang menghancurkannya dari dalam ini. Sebuah akar besi terlihat di samping dinding yang melengkung dan menembus batu yang pecah dan setiap langkah mereka yang menuruni anak tangganya dari batu kokoh itu hanya bergema di setiap jalan mereka. Vael yang berada di depan untuk memimpin jalan Sora dan Kaelith yang berada di belakangnya sedang memegang obor di tangannya yang diberikan oleh Kaelith. Kaelith mengikutinya dan melirik ke punggung Vael yang tengah memimpin jalan di deapnnya, jari-jarinya masih mencengkram erat busur barunya, dan tangannya itu berdenyut lembut seirama dengan napasnya yang tengah menggenggam busurnya. Sedangkan Sora, seperti biasa ia terdiam namun, matanya tidak pernah meninggalkan bayangan-bayangan yang bergerak di sekitar mereka dan penuh kewaspadaan juga terhadap di sekitarnya. “Kerajaan ini, dulunya hidup dalam kesombongan. Para ksatria yang dulunya memegang panji-panji diberkati oleh nafas itu sendiri bagai sumpah mereka yang melekat kepada kerajaan ini dan orang-orangnya. Kami lahir di bawah langit yang tidak pernah melupakan nama kami.” Vael memulai pembicaraannya dengan suaranya rendah dan hampir penuh hormat ketika menceritakan sedikit mengenai kerajaan Borreal kepada mereka berdua. 

“Dan kami tentunya sangat bangga ketika kami bersumpah kepada orang-orang yang menganggap kami seperti bagian darinya, sehingga kami tak bisa begitu lepas dari apa yang pernah kita sumpahi untuk menjaganya hingga kematian sendiri menjemput kami dengan hormat ketika kami melindungi orang-orang yang menganggap kami dalam bagiannya.” Tambah Vael ketika Ia berjalan terus dan pada akhirnya berhenti sesaat di ujung tangga yang menunjukkan akhir dari sebuah jalan dan menemukan tiga jalan yang bercabang dan terdapat yang diisi patung-patung wanita yang sedang menangis dan menutupi mata mereka dengan kain tengah berjejer di samping jalan dari tiga arah jalan yang bercabang itu. Dengan mata tertutup oleh kain dan beberapa di antaranya retak namun masih utuh sempurna.

“Dan sekarang, Borreal telah terlupakan oleh kesombongannya dan melahapnya hingga para ksatria yang telah bersumpah kepada kerajaan menyesalinya atas pengkhianatan yang dilakukan kerajaan terhadap sumpah mereka.” Bisiknya dengan suara lirih dan penuh dengan kesedihan karena Vael salah satu di antara ksatria-ksatria itu. Kaelith memberhentikan langkahnya dan menimpali ceritanya dengan menurunkan sedikit busurnya yang membidik ke arahnya itu. “Kau bicara seolah-olah kau masih melayaninya.” Vael yang mendengar itu, berbalik arah untuk melihat Kaelith yang menimpalinya dengan perkataannya itu. Cahaya obor memancarkan wajah Sora dan Kaelith dibelakangnya juga terdapat sinar samar-samar dari garis-garis keras pada topeng setengah baja Vael itu. “Aku hanya melayani apa yang tersisa dari sumpahnya itu dan… dari diriku yang dulu.” Vael menyipitkan matanya yang masih terus teringat akan kejadian itu masih membekas dalam kepalanya. Kaelith yang melihat Vael tertunduk lesu itu mengganti topik pembicaraan dengan bertanya padanya. “Kau masih belum mengatakan mengapa kau membantu kami?” Keheningan yang berat terjadi di antara mereka saat itu dan pertanyaan Kaelith menggema di ruangan itu.

Kemudian, dengan beban seperti zirah yang Vael kenakan, ia menjawabnya: “Karena aku gagal dalam melindungi sesuatu itu untuk tidak melanggar sumpahku.” Ia melangkah ke salah satu dari jalan yang bercabang tiga dan masuk ke dalam jalur di sebelah kiri itu. lalu Sora dan Kaelith mengikutinya dari belakang. Sambil berjalan menuju apa yang dimaksud oleh Vael, mereka bertiga sampai di ujungnya dan terlihat di samping sebuah patung yang terlihat patung-patung yang berada di samping pintu itu dan Vael menunjuk dengan jarinya ke arah sebuah pintu dengan ukiran aneh dan sepertinya sebuah aksara dengan sebuah lubang yang berada di sana sebagai kuncinya yang pintu itu tertutup rapat tepat di depan kelopak batu yang sangat aneh juga tertutup rapat oleh beberapa rantai berkarat dan tiga lubang yang ada pada pintu itu.

“Pintu itu, yang akan memperlihatkan kita mengenai makam dengan nama-nama yang sudah lama terhapus dan terlupakan seiring waktu. Istana dari para raja yang dibangkitkan lagi oleh seorang pengkhianat dan dijadikan sebagai Varnished olehnya.” Kata Vael sambil menunjuk ke arah pintu itu. Sora melihat ke arah segel pintu itu dan ia merasakan sesuatu yang janggal ketika melihat pintu itu dan darah dalam tubuh Sora seakan-akan mendidih ketika Sora melihat segel yang berada di pintu itu.

“Sumpahku adalah untuk melindungi pewaris Borreal. Tapi aku menyaksikannya sendiri jatuh ke dalam kegilaan yang tak bisa kubayangkan itu. Dan lebih buruknya lagi... Aku membantu dengan berdalih hal itu bagian dari sumpahku terhadap kerajaanku untuk membangun ritual yang mengutuk kerajaan ini dari perintah seorang raja yang terhasut oleh orang itu.” Lanjut Vael dengan suara lirih dan tangannya menyentuh gagang pedangnya itu yang berada di pinggulnya. Tangan Kaelith membeku seketika di busurnya saat mendengar apa yang baru saja diungkapkan oleh Vael tadi itu dan bertanya kepadanya dengan seolah-olah Kaelith saat ini mendengarkan pengakuan seseorang yang menghancurkan kerajaannya sendiri yang terikat oleh sumpahnya.  “Kau, apa?” Vael melihat ke arah Kaelith dengan lelah melihat reaksinya itu adalah sebuah penggambaran yang tak biasa baginya untuk mendengarkan seseorang yang menghancurkan kerajaannya sendiri dan Vael berbalik ke arah depan pintu itu untuk menghadapi mereka yang menodai seorang ksatria kerajaan yang sumpahnya telah terlanggar itu untuk menghadapi sepenuhnya dari penyesalan masa lalunya saat ini sambil melepaskan topeng usangnya itu.

Di balik topengnya itu, satu sisi wajahnya yang rusak akan bekas pertarungan-pertarungan seorang ksatria yang kondisinya itu tak lagi seperti manusia itu dengan bekas luka yang terlihat seperti rongga-rongga pada bebatuan yang akan lapuk oleh hujan dan tulang-tulang wajahnya memperlihatkan bekas luka rahasia yang sudah lama terbakar. Matanya di sisi itu berkedip samar seolah hidupnya itu sudah tak pantas untuk dipertahankan lagi untuk menaggung malunya dan berusaha untuk mempertahankan kewarasannya selagi ia masih diberi kehidupan itu. “Orang yang mengkhianati kami, menjanjikan sebuah kelahiran kembali. Bahwa, dalam Tabir yang tersingkap itu akan memurnikan kita dari segala dosa dan membuat sumpah kita seperti kekuatan bagi kami para ksatria sebagai tameng melindungi rakyat dan kerajaannya. Aku percaya padanya... sampai ia memanggil Varnished sendiri itu yang mulai bernyanyi dengan himne genosida terhadap orang-orang di kerajaan yang mebuat seluruh orang-orang mulai berubah untuk melupakan apa yang tersisa dari dalam diri mereka dan untuk membunuh satu sama lain yang telah disulap menjadi Varnished olehnya.” Suaranya bergetar bukan karena kelemahan, tetapi rasa malu dan ketakutannya yang terukir dalam dirinya hingga saat ini.

“Aku mencoba menghentikannya. Aku membunuh para Varnished itu dengan tanganku sendiri bahkan yang awalnya itu seorang rakyat dari kerajaan dan teman seperjuanganku itu yang telah dirubah olehnya menjadi Varnished itu, untuk memberanikan diriku dengan menebaskan pedangku kepada mereka. Tetapi saat itu luka di dalam hatiku juga terbuka sedikit demi sedikit hingga munculnya rasa takut akan sesuatu dari dalam diriku untuk hidup lagi dan Varnished itu turun dari langit bak menghujani kerajaan Borreal tanpa henti untuk membantai seluruh orang yang masih hidup di kerajaan itu.” Obor itu perlahan meredup seolah mendengarkan cerita yang dialami oleh ksatria yang tanpa disadari telah menjadi salah satu pengkhianat tapi masih memegang sumpahnya yang telah ia langgar itu.

Sora melangkah maju ke depan dan tangannya bergerak dengan gerakan sederhana yang terkendali dan sabar ke arah Vael yang tertunduk lesu itu. Kaelith yang memperhatikan mereka berdua itu, hanya diam saat tangan Sora menepuk ke arah bahu Vael yang ia mendengarkan kisah seseorang yang mencoba untuk melupakan dan lari dari hal yang pernah ia sesali dalam kehampaannya... dan sesuatu yang lebih dalam dari itu. Sebuah pengakuan seorang yang melabeli dirinya pengkhianat dan sebuah keakraban akan kesalahan yang ditanggung sendirian dalam waktu yang terlalu lama. Vael yang merasa bahwa Sora mencoba menghiburnya dengan mengetahui perasaan bersalahnya itu berkedip lalu berkata. “Kau... kau mengerti, bukan?” Tak ada suara yang terdengar dari Sora namun dalam keheningan terdapat sebuah jawaban yang bisa menenangkan Vael.

Kaelith menatap mereka dengan postur tubuhnya rileks serta merenggangkan tanganya ke atas dan memecah jeda dari keheningan di antara mereka berdua itu. “Jadi, apa sekarang? Ksatria yang gugur dan seorang pendiam dengan masa lalu yang susah ditebak kini berteman?” Vael hanya terkekeh pelan mendengar pertanyaan Kaelith dan ia melangkah maju mendekati pintu yang tersegel itu dan berkata. “Sekarang, kita akan membangunkan salah satu dari raja Borreal dulu itu yang sudah dihidupkan menjadi salah satu Varnished di bawah kendalinya hingga saat ini. Satu untuk setiap sumpah yang telah dikhianati.” Katanya dengan tegas dan mendapatkan kekuatannya kembali atas Sora yang menyadarkannya dan mengetahui apa yang ia rasakan sebelumnya itu. Vael menarik pedangnya dari sarungnya di ikat pinggangnya, bilahnya yang masih tajam dan tidak berkarat itu seperti itu yang telah ia jaga selama bertahun-tahun agar tidak berkarat. Tanpa ragu, dia menggoreskan bilahnya ke salah satu jari di tangannya sendiri dengan lembut dan darahnya yang kental berwarna merah dan terlihat seperti minyak yang tumpah ke lubang pertama untuk meneteskan darahnya. Segel itu mendesis dan menyala akan darahnya yang telah diteteskannya tadi.

“Satu sumpah, telah diisi untuk membuka pintu ini.” Bisiknya dengan pelan. Kaelith melangkah maju dan mencoba untuk memahami maksud dari ini dengan bertanya kepada Vael. “Tunggu dulu, kalau butuh darah sebagai kunci untuk membuka segelnya, bagaimana dengan—?!” Kaelith belum sempat menyelesaikan perkataannya namun Sora sudah melangkah di sampingnya untuk melakukan hal yang sama dengan Vael tadi untuk membukakan pintu itu dari segelnya. Tanpa gentar, dia menekan tangannya ke segel sebelah Vael. Sora tidak membutuhkan hal yang seperti Vael tadi karena lukanya yang sebelumnya melawan penyihir tadi masih baru dan ia hanya perlu menaruh tangannya yang masih basah akan darahnya itu ke dalam lubang itu dengan hanya kulit yang berdarah.

Segel itu bereaksi seketika dan bersinar bukan berwarna merah melainkan berwarna putih dan batu di belakangnya bergetar. 'Kau... kau terhubung dengan takhta. Tidak... itu terhubung oleh sesuatu di bawahnya.' bisik Vael dengan keterkejutannya yang melihat hal itu pada Sora. Kaelith yang sedari tadi memerhatikan mereka begitu tidak yakin, ia menggertakkan giginya dan mengambil pisau berburunya sendiri dari dalam kantongnya itu dan melakukan hal yang sama namun ia masih ragu dan waspada dengan apa yang terjadi. Dia menatap mereka di tepi ujung pintu itu sejenak lalu membuat sayatan kecil di jarinya untuk meneteskan darahnya di dalam lubang sebagai kunci dari segel pintu itu. Segel itu menyala berwarna hijau dan rantai yang menepel di gerbang itu bergetar seketika dan hancur seperti terkorosi oleh sesuatu hingga lenyap.

'Tiga sumpah telah dibatalkan. Tiga suara, terikat oleh kehancuran untuk mereka.' gumam Vael yang sambil melihat reaksi dari pintu itu. Namun sebelum mereka bisa masuk ke dalam pintu yang segelnya sudah terbuka itu, batu di bawah kaki mereka bergetar seketika dan hembusan angin menderu entah dari mana asalnya saat salah satu patung itu yang ditutup matanya di samping mereka bertiga, mulai bergerak.

Wraith of Binding: mereka adalah penjaga kuno yang terikat oleh sumpahnya dalam keheningan untuk menjaga sesuatu dan jiwa mereka terikat oleh orang yang membuatnya.

Patung itu menyerang dengan cakar spektral yang mencambuk Kaelith hingga Kaelith berhasil menghindarinya namun masih terkena goresan di bagian kakinya ketika kaget melihat pergerakan patung itu mulai menyerang mereka. Vael langsung ke arah patung itu dan dirinya melindungi Sora dan Kaelith sebagai tameng di antara mereka. Vael terbanting ke belakang untuk melindungi Kaelith dari serangan kedua patung itu dengan pedang yang ia hunuskan itu. Sora melangkah maju dengan cepat, pedangnya mulai ditebaskan terhadap patung-patung itu namun mereka semua mengetahui bahwa patung itu adalah batu dan tidak mungkin melawan batu yang sangat keras itu dengan pedang yang bilahnya tajam manapun. Namu, Sora tetap mencoba untuk setidaknya melukai patung itu dan terlihat bahwa pedangnya mampu memberikan goresan retakan pada patung itu dan membuatnya semakin menyerang Sora yang awalnya mencoba mengincar Kaelith dan Vael sebelumnya itu. Bentrokan diantara mereka dimulai dengan cepat dan brutal.

Gerakan Sora yang tepat dapat menembus pergerakan dan menghindari serangan dari patung itu membuat pedangnya mengiris setiap patung itu hingga akhirnya dengan satu tusukan ke arah inti patung itu dan menghancurkan patung yang menyerang ke arah mereka. Patung itu hanya bisa diam saat ia hancur menjadi serpihan batu berkeping-keping ketika intinya telah rusak. Dan keheningan kembali terjadi setelah bentrokan dengan patung itu. Mereka berdiri terengah-engah, terutama Sora yang memiliki bekas luka sebelumnya ditambah dengan memar dan pendarahan yang keluar dari setiap luka yang terbuka kembali itu mengotori lantai dibawahnya dengan tetesan darahnya.

Kaelith menyeka lukanya di kaki yang berhasil menghindari serangan itu dengan sebuah goresan cakar dari patung tadi membekas di kakinya sembari berkata. 'Sambutan yang bagus untuk menyambut tamu.' Vael yang mendapat serangan langsung dari patung itu, memaksakkan dirinya untuk bangkit dan berjalan ke arah pintu yang sudah terbebaskan dari segel itu. 'Sebaiknya kita harus beristirahat dahulu. Segel itu tidak akan tertutup kembali ketika sudah terlepas dan kita masih punya banyak waktu untuk berbenah sebelum menghadapi raja dari Varnished mungkin.' Ujarnya dengan berjalan ke samping pintu itu dan duduk di atas tanah dengan meletakkan pedangnya.Sora dan Kaelith setuju akan hal itu dan mereka beristirahat di mana Vael mengistirahatkan tubuhnya di sana. Kaelith menaruh busurnya di atas tanah dan Sora duduk dengan nafasnya yang pendek akan merasakan kembali lukanya yang terbuka namun ia mencoba untuk tetap fokus dan mengatur nafasnya teratur.

Kaelith menatap Sora yang lukanya dibalut olehnya sebelumnya kini kembali terbuka dan tak tahu lagi apa yang dirasakan Sora itu terhadap lukanya itu, lalu ia menatap Vael yang hanya melihat ke arah pedangnya yang masih mengkilap dan dijaganya layaknya bagian dari diirnya dan simbol dari ksatria Borreal itu. Setelah jeda yang panjang, Kaelith memecah keheningan dengan bertanya dengan pelan kepada Vael: 'Kenapa kau benar-benar datang ke sini, Vael? Apakah untuk penebusanmu itu atau membalaskan dendammu?' Sang ksatria itu menatap api obornya yang hampir mati itu menjawab pertanyaan Kaelith. “Karena dalam mimpiku, aku masih mendengar anak itu menjerit dan yang tidak bisa kuselamatkan atas apa yang pernah kulakukan terhadap kerajaan ini beserta orang-orang di dalamnya.” Mata Vael beralih ke Sora dan untuk pertama kalinya, Sora merasakan Vael bukan melihat ke arahnya dan ia melihat ke arah belakangnya dengan sesuatu yang lain dari keheningan yang jauh di sana dan terjaga.

Sebuah pertanyaan atau sebuah jawaban untuk mereka yang sedang beristirahat? Atau mungkin... sebuah kenangan yang dilupakan akan sebuah kesalahan yang tak pernah ingin diingat kembali?";

                $paragraf = preg_split('/(\r\n|\n|\r){2,}/', $naskahLengkap);
                $naskahTerformat = '';
                foreach ($paragraf as $p) {
                    if (!empty(trim($p))) {
                        $naskahTerformat .= "<p>" . trim(nl2br($p)) . "</p>";
                    }
                }
            @endphp

            <div style="font-size: 1.1rem; line-height: 1.8;">
                {!! $naskahTerformat !!}
            </div>

            <hr class="my-5">

            <div class="d-flex justify-content-center gap-3">
                <a href="/story/the-unkindled/bab-empat" class="btn btn-lg btn-contrast">Kembali ke Bab Sebelumnya</a>
                <a href="/story/the-unkindled" class="btn btn-lg btn-contrast">Kembali ke Halaman Novel</a>
            </div>

        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    document.cookie = "lastRead_the-unkindled=bab-lima; path=/; max-age=31536000; SameSite=Lax";
</script>
@endpush